### PR TITLE
Fix: solar automation time calculation

### LINKED ISSUE #6827: [Bug] Location base automation does not work anymore since update
# Bug Report

## Bug Description
After the update of 20 Sept to 4.9.35 the automatic darkening based on location did not work anymore, It happens on any website.

## Website Address
Any

## Steps To Reproduce
Fill in a location (in my example 44 N and 6 E) and when getting dark, the dar reader does not enable automatically anymore. Same applies to sunrise.

## Expected Behavior
It should work as previously, i.e. automatically darken at sunset at the provided location.

## Actual Behavior
Automation does not work.

## System Information

- OS: macOS
- Browser: Firefox 92
- Dark Reader Version: 4.9.35

## Additional Context
As long as this does not work, where can I obtain the 4.9.34 ?

Screenshot 2021-09-21 at 07 46 00
>

### PR DESCRIPTION
**Pull request by bershanskiy**
Fixes #6827.

CC @Gusted

### CODE REVIEW

File: src/utils/time.ts [hunk 1]
```diff
@@ -263,41 +263,31 @@ export function nextNightAtLocation(
         return date.getTime() + getDuration({days: 1});
     }
 
-    const sunriseTime = time.sunriseTime;
-    const sunsetTime = time.sunsetTime;
+    const [time1, time2] = time.sunriseTime < time.sunsetTime ? [time.sunriseTime, time.sunsetTime] : [time.sunsetTime, time.sunriseTime];
```
Comment (Gusted) [inline src/utils/time.ts:266]: Same thing, could be more verbose, e.g. FirstTimeOnDay or something in that way that indicates it's the lowest time of the 2 times.

File: src/utils/time.ts [hunk 2]
```diff
@@ -250,7 +250,7 @@ export function isNightAtLocation(
     return isInTimeIntervalUTC(sunsetTime, sunriseTime, currentTime);
 }
 
-export function nextNightAtLocation(
+export function nextChangeAtLocation(
```
Comment (Gusted) [inline src/utils/time.ts:253]: Could be a little bit more verbose, e.g. `nextTimeChangeAtLocation`

**Review by Gusted — APPROVED** [review]
Functionality is all good for me, you can leave the 2 comments for another PR if you'd like.

**Review by alexanderby — APPROVED** [review]
