### PR TITLE
Ensure proper destroy of manager 

### LINKED ISSUE #6075: Styles are cached
Dark Reader apparently now caches styles. That makes it impossible to fix the broken style when visiting websites based on mdBook (most of which are consistently broken all the time). The only solution is to turn off Dark Reader, refresh the page, and make sure the styles are fully loaded before toggling it for the first time.

Thanks to this caching behavior it is even more inconvenient to fix broken webpages.

# Broken Website
## Website
https://poga.github.io/lua53-notes
Most other websites based on mdBook 

## How to Reproduce
visit site

## Expected behavior
Syntax highlighting exists, header border isn't way too bright, the entire page doesn't share one background color

## Actual behavior
The exact opposite

## Screenshots
Broken:
image

Non-broken:
image

## System Information
- OS: Microsoft Windows 10 Home build 19041
- Browser: Google Chrome 91.0.4472.77 (Official Build) (64-bit) (cohort: Stable)
- Dark Reader Version: 4.9.33

## Additional context
Possibly similar problem to #3540?

### LINKED ISSUE #6135: [Broken Website] Quillbot lot of buttons and text missing
# Broken Website
## Website

https://quillbot.com/premium

## Expected behavior

Buttons and text to be visible

## Actual behavior

Not visible buttons

## Screenshots

image

image

## System Information

- OS:  Windows 10
- Browser:  Edge stable
- Dark Reader Version:  4.9.33

### PR DESCRIPTION
**Pull request by Gusted**
- Ensure that `LoadingEnd` is called, to check if the `fallbackStyle` can be removed.
- Ensure that we reject the promise of `linkLoading`
- Ensure that when dark reader is toggled that the map/set is cleared.
- Add a bunch of debugging code to make it easier next time to debug these kinds of issues.
- Error on loading styles that doesn't have a `href`

- Resolves #6075
- Resolves #6135

### CODE REVIEW

**Comment by Gusted** [comment]
If someone want's to test it out:
[binaries.zip](https://github.com/darkreader/darkreader/files/6682344/binaries.zip)

**Comment by Gusted** [comment]
@Karmalakas could you try the binary above? The other issue very resembles your current situation at gurushots.

**Comment by arche-dev** [comment]
> If someone want's to test it out:
> [binaries.zip](https://github.com/darkreader/darkreader/files/6682344/binaries.zip)

Syntax highlighting works, so other broken things also should be working :>

**Comment by Gusted** [comment]
> so other broken things also should be working :>

Could be, at least more situations should be covered now and not result in a fallback style being displayed.

File: src/inject/dynamic-theme/index.ts [hunk 1]
```diff
@@ -265,7 +267,9 @@ const cancelRendering = function () {
 function onDOMReady() {
     if (loadingStyles.size === 0) {
         cleanFallbackStyle();
+        return;
     }
+    logWarn(loadingStyles);
```
Comment (alexanderby) [inline src/inject/dynamic-theme/index.ts:272]: Maybe more clear message should be here?

File: src/inject/dynamic-theme/style-manager.ts [hunk 2]
```diff
@@ -81,6 +81,9 @@ document.addEventListener('__darkreader__inlineScriptsAllowed', () => {
     canOptimizeUsingProxy = true;
 });
 
+export let loadingLinkStyle = 0;
```
Comment (alexanderby) [inline src/inject/dynamic-theme/style-manager.ts:84]: Looks like it shouldn't be exported

File: src/inject/dynamic-theme/style-manager.ts [hunk 3]
```diff
@@ -145,6 +148,7 @@ export function manageStyle(element: StyleElement, {update, loadingStart, loadin
 
     let isLoadingRules = false;
     let wasLoadingError = false;
+    let loadingLinkID = 0;
```
Comment (alexanderby) [inline src/inject/dynamic-theme/style-manager.ts:151]: Let's call it counter instead of ID. It becomes ID when you pass it into a function where the reference to the counter is lost.

File: src/inject/dynamic-theme/style-manager.ts [hunk 4]
```diff
@@ -162,7 +166,9 @@ export function manageStyle(element: StyleElement, {update, loadingStart, loadin
                 isStillLoadingError(accessError)
             ) {
                 try {
-                    await linkLoading(element);
+                    loadingLinkID = ++loadingLinkStyle;
```
Comment (alexanderby) [inline src/inject/dynamic-theme/style-manager.ts:169]: Hmm, looks like you have to use `const` here, so each style has its own ID. Also there is a naming convention to use `Id` instead of `ID` in JS and other similar languages, e.g. `document.getElementById`.

File: src/inject/dynamic-theme/style-manager.ts [hunk 5]
```diff
@@ -422,6 +428,11 @@ export function manageStyle(element: StyleElement, {update, loadingStart, loadin
         pause();
         removeNode(corsCopy);
         removeNode(syncStyle);
+        loadingEnd();
+        if (loadingLinkID && loadingLinkStyles.has(loadingLinkID)) {
```
Comment (alexanderby) [inline src/inject/dynamic-theme/style-manager.ts:432]: I think you need a boolean here, e.g. `isLinkLoading` instead of `loadingLinkID`. Or maybe don't need at all.

File: src/inject/dynamic-theme/style-manager.ts [hunk 6]
```diff
@@ -422,6 +428,11 @@ export function manageStyle(element: StyleElement, {update, loadingStart, loadin
...
+            loadingLinkStyles.get(loadingLinkID)();
```
Comment (alexanderby) [inline src/inject/dynamic-theme/style-manager.ts:433]: Looks a bit ( )( ). Try putting a callback into another variable.

File: src/inject/dynamic-theme/style-manager.ts [hunk 7]
```diff
@@ -465,20 +476,23 @@ export function manageStyle(element: StyleElement, {update, loadingStart, loadin
     };
 }
 
-async function linkLoading(link: HTMLLinkElement) {
+async function linkLoading(link: HTMLLinkElement, loadingID: number) {
```
Comment (alexanderby) [inline src/inject/dynamic-theme/style-manager.ts:479]: Use `Id` for `ID`

File: src/inject/dynamic-theme/style-manager.ts [hunk 8]
```diff
@@ -465,20 +476,23 @@ export function manageStyle(element: StyleElement, {update, loadingStart, loadin
...
             cleanUp();
+            logInfo(`Linkelement ${loadingID} has been loaded`);
             resolve();
         };
         const onError = () => {
             cleanUp();
-            reject(`Link loading failed ${link.href}`);
+            reject(`Linkelement ${loadingID} couldn't be loaded. ${link.href}`);
         };
+        loadingLinkStyles.set(loadingID, reject);
```
Comment (alexanderby) [inline src/inject/dynamic-theme/style-manager.ts:495]: As far as you put rejectors here, give `loadingLinkStyles` a proper name. Also, take a look if you can use `link` element itself as a key in a WeakSet, Set, WeakMap or Map instead of numeric IDs.

**Review by alexanderby — CHANGES_REQUESTED** [review]

**Comment by Karmalakas** [comment]
> @Karmalakas could you try the binary above? The other issue very resembles your current situation at gurushots.

This didn't help. Same issue persists
image

Will keep monitoring still, because this kind of popup is not the main issue

File: src/inject/dynamic-theme/style-manager.ts (hunk 2 above)
Comment (Gusted) [reply src/inject/dynamic-theme/style-manager.ts:84]: Good catch 😄

Comment (Gusted) [reply src/inject/dynamic-theme/style-manager.ts:84]: Good catch 😄

File: src/inject/dynamic-theme/index.ts [hunk 9]
```diff
@@ -459,6 +464,8 @@ export function removeDynamicTheme() {
     });
     shadowRootsWithOverrides.clear();
     forEach(styleManagers.keys(), (el) => removeManager(el));
+    loadingStyles.clear();
+    storedRejectorsForLoadingLinks.clear();
```
Comment (alexanderby) [inline src/inject/dynamic-theme/index.ts:468]: I feel like a bit of Encapsulation (OOP) should be here (even though it's one line): This file should know as few details as possible, so you should import some method for cleaning up something.

File: src/inject/dynamic-theme/style-manager.ts [hunk 10]
```diff
@@ -81,6 +81,9 @@ document.addEventListener('__darkreader__inlineScriptsAllowed', () => {
     canOptimizeUsingProxy = true;
 });
 
+let loadingLinkCounter = 0;
+export const storedRejectorsForLoadingLinks = new Map<number, (reason?: any) => void>();
```
Comment (alexanderby) [inline src/inject/dynamic-theme/style-manager.ts:85]: "stored" part can be removed

File: src/inject/dynamic-theme/style-manager.ts [hunk 11]
```diff
@@ -422,6 +427,13 @@ export function manageStyle(element: StyleElement, {update, loadingStart, loadin
         pause();
         removeNode(corsCopy);
         removeNode(syncStyle);
+        loadingEnd();
+        let reject: (reason?: any) => void;
+        if (storedRejectorsForLoadingLinks.has(loadingLinkId)) {
+            reject = storedRejectorsForLoadingLinks.get(loadingLinkId);
+            storedRejectorsForLoadingLinks.delete(loadingLinkId);
+        }
+        reject && reject();
```
Comment (alexanderby) [inline src/inject/dynamic-theme/style-manager.ts:436]: You can put "reject" variable and it's call into the "if" scope.

**Review by alexanderby — CHANGES_REQUESTED** [review]

**Review by alexanderby — APPROVED** [review]
