### PR TITLE
Better Idle performance

### LINKED ISSUE #1125: checkForUpdate polling causes significantly increased CPU usage on some sites
#### Overview
I recently noticed a significant increase in Chromium's idle CPU usage and identified darkreader as the culprit. My methodology involves observing the relevan't Tab's CPU usage in the Chromium task manager before and after switching from the Dynamic theme to Static/Filter but also verified it by disabling the offending code, see below.

#### Impact
The CPU usage on Google Search/Youtube homepages goes up from about 2-4% in idle to 15-20% in idle (as seen in Chromium's task manager).

Due to the use of `requestAnimationFrame` to schedule polling this only seems to happen when the page is currently visible in a browser window limiting the impact somewhat.

#### Reproducing
I belive the polling of stylesheet changes in `checkForUpdate` is causing this high load. If I comment out the `requestAnimationFrame(checkForUpdate)` call in `src/inject/dynamic/style-manager.ts` the CPU usage reliably goes back to baseline levels.

#### Fix
I'm not really sure what kind of changes are being watched for here, is this only for first time load stuff or is this also intended to catch changes after the site finished loading? I would send a patch but my javascript foo is very rusty, but given some direction I would be happy to help implementing a fix.

Would it be possible to get notified of these stylesheet changes instead of polling? If not throttling the polling as the site reaches a steady state might be a decent fix.

Personally I might be happy just being able to set the theme engine per-site but that seems crude as a fix :)

### LINKED ISSUE #2070: [Bug] DR causes massive CPU issues when active on inspected pages (Chromium devtools)
Google Chrome Version 80.0.3987.132 (Official Build) (64-bit)
DR 4.8.9
Win 8.1

This has been a problem I've been running into for a long time, and I finally got around to troubleshooting. To my surprise, seems like DR was the problem.

Basically, when you inspect most pages DR is active on, once you hover the DOM tree, CPU spikes through the roof, at least an additional 50-70%, often more, and never releases. I made a [screen record](https://streamable.com/vjd48) to demo, first without DR enabled, then with it enabled. CoreTemp is active in the system tray, and the green indicator is CPU. Bear in mind, OBS is running which averages about 5-10% CPU.

As you'll see, without DR active, hovering the DOM in devtools will very briefly spike ~5-10% when the mouse is active, and almost immediately normalize once the mouse stops. When DR is active, hovering the DOM tree causes CPU to skyrocket and never release. OBS actually throws an encoding warning, the CPU spikes so dramatically.

This is not true for every page DR is active on. In my testing, a few seemed unaffected (Github for example), but the vast majority are affected.

Steps to repro:

* New Google Chrome profile

* New DR install

* Visit:  https://example.com/

* Open devtools and hover DOM tree nodes while observing CPU

### LINKED ISSUE #3905: [BUG] checkIfDefined is doing nothing but wasting CPU
### **Describe the bug**

The current implementation can and is endlessly looping so long the elements are not defined which in some cases won't be and due to the logic used in this function it will somehow use noticeable (on low-medium spec CPU) CPU Utilization.

e.g. https://mail.google.com

### **Steps to reproduce**

- Go to mail.google.com
- Open performance tab in Dev tools
- Get a fresh performance `ctrl +e` after the page has been fully loaded.
- See that even that checkIfDefined is still being called in a animationFrame alongside checkForUpdate(expected)

### **Expected behavior**

Not using CPU or some other implementation to prevent this, not even sure what `:defined` has to do with Shadow DOM's.

### **Actual behavior**

It's using CPU utilization even in `idle` when not needed

### **System Information:**
 - OS: Windows 10
 - Browser: Vivaldi(3.4.2066.76)
 - Dark Reader version: 4.9.21

### **Additional context**

More info about this https://github.com/darkreader/darkreader/issues/3811#issuecomment-712695274

### PR DESCRIPTION
**Pull request by Gusted**
- Uses a prototype override to detect changes in the style.
- This will improve idle CPU consumption of the browser as it won't have to run `requestAnimationFrame` to detect changes.
- Most of the understanding of prototype overriding came from @tophf's [XRay-Styler](https://github.com/tophf/XRayStyler/). Credits to him!
- NO WINDOW POLLUTING!!
- Resolves #2070
- Resolves #1125
- Resolves #3905

### CODE REVIEW

File: src/inject/dynamic-theme/style-manager.ts [hunk 1]
```diff
@@ -318,44 +318,67 @@ export function manageStyle(element: StyleElement, {update, loadingStart, loadin
...
+
+                // Create a new Event so it can be dispatched.
+                const event = new Event('updateSheet');
+
+                // Create the proxy function that should be identicial to the native one's.
+
+                function proxyAddRule(selector, style, index) {
+                    addRuleFunction.value.call(this, selector, style, index);
+                    this.ownerNode.dispatchEvent(event);
+                    // Check why it returns -1 https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/addRule#Return_value.
```
Comment (Gusted) [inline src/inject/dynamic-theme/style-manager.ts:347]: https://drafts.csswg.org/cssom/#dom-cssstylesheet-deleterule check definition 8.
https://searchfox.org/mozilla-central/source/layout/style/StyleSheet.cpp#640 Firefox return 1;
https://github.com/chromium/chromium/blob/master/third_party/blink/renderer/core/css/css_style_sheet.cc#L442 Chromium return 1;

File: src/inject/dynamic-theme/style-manager.ts [hunk 2]
```diff
@@ -318,44 +318,67 @@ export function manageStyle(element: StyleElement, {update, loadingStart, loadin
...
+                    return -1;
+                }
+                function proxyInsertRule(rule, index) {
+                    // Cache the return value of insertRule as insertRule has the chance to not return the originial index.
```
Comment (Gusted) [inline src/inject/dynamic-theme/style-manager.ts:351]: https://github.com/chromium/chromium/blob/master/third_party/blink/renderer/core/css/css_style_sheet.cc#L322-L367 can return `0` due to errors.
https://searchfox.org/mozilla-central/source/layout/style/StyleSheet.cpp#588-597 can return `0` due to errors.

**Comment by Gusted** [comment]
[darkreader.zip](https://github.com/darkreader/darkreader/files/5470038/darkreader.zip)
Debug copies of this Branch.

And a test page it should make the background-color `rgb(89, 0, 16)`
[aaa.zip](https://github.com/darkreader/darkreader/files/5470039/aaa.zip)

**Comment by ddnexus** [comment]
Just tried the debug copy on the same system that was consuming quite a lot on idle, and it works as expected now. 
Great job! :1st_place_medal:

**Comment by Gusted** [comment]
> 
> 
> Just tried the debug copy on the same system that was consuming quite a lot on idle, and it works as expected now.
> Great job! 🥇

Great to hear that!

**Comment by Gusted** [comment]
Cleaned up a lot of code and made it less messy and more understandable also fixed some bugs. https://github.com/darkreader/darkreader/pull/4005/commits/9e7b381b5efef2f9e85ccde6745731b9bd8e5450

Improved the clean up of the prototype override. https://github.com/darkreader/darkreader/pull/4005/commits/1044344498d9d836d0aa73339634386f9b4b6754

here the build binaries for Firefox & Chromium.
[darkreader.zip](https://github.com/darkreader/darkreader/files/5471852/darkreader.zip)

It should be stable enough now.

**Comment by ddnexus** [comment]
I retried both builds, the difference between dynamic and non-dynamic mode on idle is almost 0 almost on all pages that I tried.

However that doesn't seem to apply to the gmail inbox page. In that case the improvement is just marginal (i.e. CPU difference on idle is still about 10% more for dynamic).

Maybe that's worth some more analysis, because it could be a more general case not limited to gmail.

Here is the profile:
[Profile-20201102T105255.zip](https://github.com/darkreader/darkreader/files/5472731/Profile-20201102T105255.zip)

**Comment by Gusted** [comment]
> However that doesn't seem to apply to the gmail inbox page. In that case the improvement is just marginal (i.e. CPU difference on idle is still about 10% more for dynamic).
> 
> Maybe that's worth some more analysis, because it could be a more general case not limited to gmail.
> 
> Here is the profile:
> [Profile-20201102T105255.zip](https://github.com/darkreader/darkreader/files/5472731/Profile-20201102T105255.zip)

The faulty code is https://github.com/darkreader/darkreader/blob/master/src/inject/dynamic-theme/watch.ts#L47

**Comment by ddnexus** [comment]
Good that you already know the cause, but is there also a solution?

**Comment by Gusted** [comment]
> Good that you already know the cause, but is there also a solution?

I have a idea for a solution that requires a rewrite of this `defined` logic so expect a new commit to fix this within a few days.

File: src/inject/dynamic-theme/index.ts [hunk 3]
```diff
@@ -106,16 +109,28 @@ function createStaticStyleOverrides() {
         `}`
     ].join('\n');
     document.head.insertBefore(variableStyle, inlineStyle.nextSibling);
-    setupStylePositionWatcher(variableStyle, 'variables');
+    setupNodePositionWatcher(variableStyle, 'variables');
+
+    const proxyScript = createOrUpdateElement('darkreader--proxy', undefined, 'script');
+    proxyScript.textContent = `// First get the originial 'native code' of the function.
```
Comment (alexanderby) [inline src/inject/dynamic-theme/index.ts:115]: I suggest you to move the whole function into a separate file. Avoid polluting window scope.
E.g. use something like
```javascript
import {injectProxy} from './stylesheet-proxy';
proxyScript.textContent = `(${goodFunctionName})()`;
```
It will convert the function to a string and execute.

File: src/inject/dynamic-theme/index.ts [hunk 4]
```diff
@@ -422,6 +437,18 @@ export function createOrUpdateDynamicTheme(filterConfig: FilterConfig, dynamicTh
     }
 }
 
+function removeProxy() {
+    const proxy = document.head.querySelector('.darkreader--proxy');
+    if (proxy) {
+        const Dproxy = document.createElement('script');
```
Comment (alexanderby) [inline src/inject/dynamic-theme/index.ts:443]: `Dproxy`? :) Try some different meaningful lowercase name.

File: src/inject/dynamic-theme/index.ts [hunk 5]
```diff
@@ -106,16 +109,28 @@ function createStaticStyleOverrides() {
...
+    proxyScript.textContent = `// First get the originial 'native code' of the function.
+        window['addRuleFunction'] = Object.getOwnPropertyDescriptor(CSSStyleSheet.prototype, 'addRule');
+        window['insertRuleFunction'] = Object.getOwnPropertyDescriptor(CSSStyleSheet.prototype, 'insertRule');
+        window['deleteRuleFunction'] = Object.getOwnPropertyDescriptor(CSSStyleSheet.prototype, 'deleteRule');
+        window['removeRuleFunction'] = Object.getOwnPropertyDescriptor(CSSStyleSheet.prototype, 'removeRule');
+        ${injectProxy.toString()}
+        ${removeProxyOnPrototype.toString()}
+        injectProxy();`;
+    document.head.insertBefore(proxyScript, variableStyle.nextSibling);
+    setupNodePositionWatcher(proxyScript, 'proxy');
```
Comment (alexanderby) [inline src/inject/dynamic-theme/index.ts:124]: I don't think there's a need to watch for its position.

File: src/inject/dynamic-theme/index.ts [hunk 6]
```diff
@@ -25,50 +26,52 @@ let filter: FilterConfig = null;
...
 let isIFrame: boolean = null;
 
-function createOrUpdateStyle(className: string, root: ParentNode = document.head || document) {
-    let style = root.querySelector(`.${className}`) as HTMLStyleElement;
-    if (!style) {
-        style = document.createElement('style');
-        style.classList.add('darkreader');
-        style.classList.add(className);
-        style.media = 'screen';
+function createOrUpdateElement(className: string, root: ParentNode = document.head || document, elementType = 'style') {
```
Comment (alexanderby) [inline src/inject/dynamic-theme/index.ts:29]: Let's create 2 functions: one for style and one for script, because it is not obvious that calling `createOrUpdateElement(className)` returns a style element.

File: src/inject/dynamic-theme/style-manager.ts [hunk 7]
```diff
@@ -318,50 +318,22 @@ export function manageStyle(element: StyleElement, {update, loadingStart, loadin
...
-                update();
-            }
-            rulesCheckFrameId = requestAnimationFrame(checkForUpdate);
-        };
-        checkForUpdate();
-    }
-
-    function unsubscribeFromSheetChanges() {
-        cancelAnimationFrame(rulesCheckFrameId);
+        element.addEventListener('updateSheet', update);
```
Comment (alexanderby) [inline src/inject/dynamic-theme/style-manager.ts:322]: There's a small chance of events name collision. Add some `darkreader` prefix to the event name.

File: src/inject/dynamic-theme/stylesheet-proxy.ts [hunk 8]
```diff
@@ -0,0 +1,43 @@
+export function injectProxy() {
+    // Create a new Event Object that can be dipatched on elements.
+    const updateSheetEvent = new Event('updateSheet');
+
+    // Create the proxy function that should be identicial to the native one's.
+    function proxyAddRule(selector?: string, style?: string, index?: number): number {
+        window['addRuleFunction'].value.call(this, selector, style, index);
+        this.ownerNode.dispatchEvent(updateSheetEvent);
+        // Should always returns -1 https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/addRule#Return_value.
```
Comment (alexanderby) [inline src/inject/dynamic-theme/stylesheet-proxy.ts:9]: You can remove all comments except this one.

File: src/inject/dynamic-theme/stylesheet-proxy.ts [hunk 9]
```diff
@@ -0,0 +1,43 @@
...
+        this.ownerNode.dispatchEvent(updateSheetEvent);
+    }
+
+    function proxyRemoveRule(index?: number): void {
+        window['removeRuleFunction'].value.call(this, index);
+        this.ownerNode.dispatchEvent(updateSheetEvent);
+    }
+
+    // Define the prototype of the CSSStyleSheet to use the proxy function.
+    Object.defineProperty(CSSStyleSheet.prototype, 'addRule', {...window['addRuleFunction'], value: proxyAddRule});
```
Comment (alexanderby) [inline src/inject/dynamic-theme/stylesheet-proxy.ts:31]: So, try doing the same without polluting the global scope.

**Comment by narcolepticinsomniac** [comment]
Needless to say, this PR is awesome as well. Previously, Chromium devtools were practically unusable when the dynamic theme was active on a page. This resolves whatever weird conflict element highlighting has with `requestAnimationFrame`, and the non-stop, ridiculous CPU consumption that comes along with it. Also resolves some other weird bugs I've encountered on a somewhat regular basis on certain sites.

File: src/inject/dynamic-theme/stylesheet-proxy.ts [hunk 10]
```diff
@@ -0,0 +1,43 @@
...
+    Object.defineProperty(CSSStyleSheet.prototype, 'insertRule', {...window['insertRuleFunction'], value: proxyInsertRule});
+    Object.defineProperty(CSSStyleSheet.prototype, 'deleteRule', {...window['deleteRuleFunction'], value: proxyDeleteRule});
+    Object.defineProperty(CSSStyleSheet.prototype, 'removeRule', {...window['removeRuleFunction'], value: proxyRemoveRule});
+}
+
+export function removeProxyOnPrototype() {
+    // Define the prototype of the CSSStyleSheet to the orginial function.
+    Object.defineProperty(CSSStyleSheet.prototype, 'addRule', {...window['addRuleFunction']});
```
Comment (alexanderby) [inline src/inject/dynamic-theme/stylesheet-proxy.ts:39]: Instead try launching the cleanup by dispatching a custom event on document, or saving a removal function into window scope like `__darkreader__removeCSSStyleSheetProxy__()` (more ugly).

**Review by alexanderby — CHANGES_REQUESTED** [review]

**Comment by alexanderby** [comment]
One ugly thing about adding style is that some sites can have CSP no inline style etc.

File: src/inject/dynamic-theme/stylesheet-proxy.ts [hunk 11]
```diff
@@ -0,0 +1,46 @@
+export function injectProxy() {
+    if (!window['__darkreader__addRuleFunction']) {
+        window['__darkreader__addRuleFunction'] = Object.getOwnPropertyDescriptor(CSSStyleSheet.prototype, 'addRule');
```
Comment (alexanderby) [inline src/inject/dynamic-theme/stylesheet-proxy.ts:3]: You can just store the descriptors in the function scope like `const addRuleDescriptor = Object.getOwnPropertyDescriptor(CSSStyleSheet.prototype, 'addRule')` :)

**Review by alexanderby — CHANGES_REQUESTED** [review]

**Review by alexanderby — APPROVED** [review]
Great!

Now the new problem arises: if some style sheet is changed synchronously many times, the update will be called too often. The `throttle` function can come into rescue. Or maybe `queueMicrotask` can help there. Let it be a problem of another PR.

**Comment by Gusted** [comment]
> Let it be a problem of another PR.

It will be a issue. I have spend too many hours on this PR as well.

**Comment by Gusted** [comment]
> Good that you already know the cause, but is there also a solution?

#4055 It's possible however I still know half of what the defined Elements, so it's up to @alexanderby for this one.
