### PR TITLE
 Remove manger when Style becomes disabled

### LINKED ISSUE #3841: [Broken Website] infinitysearch.co
**Website**
infinitysearch.co

**How to Reproduce**
An example of this is
> 1. Go to infinitysearch.co

**Expected behavior**
sshot-005

**Actual behavior**
sshot-004

After reenable dark reader it will look like the above one.

**System info:**
 - OS: Windows 10
 - Browser: Firefox
 - Darkreader Version: 4.9.17

### PR DESCRIPTION
**Pull request by Gusted**
- Remove the manager of an StyleElement when the disabled attribute is being set.
- Add test cases to not handle disabled StyleElements.
- Fixes bug where the previous link wasn't removed.
- `document.head` -> `container` in `should move override` test.
- Resolves #3841

### CODE REVIEW

File: src/inject/dynamic-theme/watch.ts [hunk 1]
```diff
@@ -161,16 +161,21 @@ export function watchForStyleChanges(currentStyles: StyleElement[], update: (sty
...
     function handleAttributeMutations(mutations: MutationRecord[]) {
         const updatedStyles = new Set<StyleElement>();
+        const removedStyles = new Set<StyleElement>();
         mutations.forEach((m) => {
-            if (shouldManageStyle(m.target) && m.target.isConnected) {
-                updatedStyles.add(m.target as StyleElement);
+            if (m.target.isConnected) {
+                if (shouldManageStyle(m.target)) {
+                    updatedStyles.add(m.target as StyleElement);
+                } else if ((m.target as HTMLLinkElement).disabled && shouldManageStyle(m.target, {disableDisabled: true})) {
```
Comment (alexanderby) [inline src/inject/dynamic-theme/watch.ts:169]: Very nice, but ... is there a need in options.disableDisabled? Funny name BTW, should we disable disabled or enable disabled? 🤣 

Maybe replace with `} else if (m.target instanceof HTMLLinkElement && m.target.disabled) {`, it is not an expensive operation and code looks simpler.

File: src/inject/dynamic-theme/watch.ts [hunk 2]
```diff
@@ -161,16 +161,21 @@ export function watchForStyleChanges(currentStyles: StyleElement[], update: (sty
 
     function handleAttributeMutations(mutations: MutationRecord[]) {
         const updatedStyles = new Set<StyleElement>();
+        const removedStyles = new Set<StyleElement>();
         mutations.forEach((m) => {
```
Comment (alexanderby) [inline src/inject/dynamic-theme/watch.ts:165]: Worth using destructuring `{target}` by the way.

**Review by alexanderby — CHANGES_REQUESTED** [review]

File: src/inject/dynamic-theme/watch.ts (hunk 1 above)
Comment (Gusted) [reply src/inject/dynamic-theme/watch.ts:169]: > Very nice, but ... is there a need in options.disableDisabled? Funny name BTW, should we disable disabled or enable disabled? 

`anPossibleCheckToExcludeDisableFromBeingTestedInTheCondition`

**Review by alexanderby — APPROVED** [review]
