### PR TITLE
Export/Import

### LINKED ISSUE #615: Import / Export Site List
Dark Reader has improved enough that I'm considering switching it on by default and only disabling it for sites that are broken.  However, currently I don't want to do that due to my inability to switch back at a later stage whilst keeping my enabled / disabled sites list.

A way to export / import a list so that I don't have this concern anymore would be great.

### LINKED ISSUE #2014: [Request] Export site list
Hello there,

Thank you for such a great extension! I believe having an export option for site list will be useful. If not able to implement this, please guide me on a way to export the list.

Have a great day everyone!

### PR DESCRIPTION
**Pull request by Gusted**
Resolves #615 
Resolves #2014

### CODE REVIEW

File: src/ui/controls/input/index.tsx [hunk 1]
```diff
@@ -0,0 +1,17 @@
+import {m} from 'malevic';
```
Comment (alexanderby) [inline src/ui/controls/input/index.tsx:1]: I don't think there's a need in it, especially that it's hard to style it. `<input>` cannot have child nodes.

File: src/ui/popup/body/style.less [hunk 2]
```diff
@@ -146,6 +146,7 @@
     @import "../page-viewer/style.less";
     @import "../settings-page/style.less";
     @import "../automation-page/style.less";
+    @import "../automation-page/style.less";
```
Comment (alexanderby) [inline src/ui/popup/body/style.less:149]: Check imported name

File: src/ui/popup/manage-settings-page/export-settings.tsx [hunk 3]
```diff
@@ -0,0 +1,21 @@
+import {m} from 'malevic';
+import {ViewProps} from '../types';
+import {Button} from '../../controls';
+
+export default function ExportButton(props: ViewProps) {
+    function exportSettings() {
+        const data = JSON.stringify(props.data.settings);
+        const a = document.createElement('a');
```
Comment (alexanderby) [inline src/ui/popup/manage-settings-page/export-settings.tsx:8]: Move file save function into `src/ui/utils.ts` use arguments `name: string` and `content: string`

File: src/ui/popup/manage-settings-page/import-settings.tsx [hunk 4]
```diff
@@ -0,0 +1,35 @@
+import {m} from 'malevic';
+import {ViewProps} from '../types';
+import ControlGroup from '../control-group';
+import {Input} from '../../controls';
+import {UserSettings} from '../../../definitions';
+
+export default function ImportButton(props: ViewProps) {
+    function importSettings() {
+        if (this.files.length > 0) {
+            const reader = new FileReader();
```
Comment (alexanderby) [inline src/ui/popup/manage-settings-page/import-settings.tsx:10]: Use `openFile` function from `src/ui/utils.ts`

File: src/ui/popup/manage-settings-page/import-settings.tsx [hunk 5]
```diff
@@ -0,0 +1,35 @@
...
+            }
+            reader.readAsText(this.files[0]);
+        }
+
+    }
+
+    return (
+        <ControlGroup>
+            <ControlGroup.Control>
+                <Input onchange={importSettings} class="File-Input">
```
Comment (alexanderby) [inline src/ui/popup/manage-settings-page/import-settings.tsx:29]: Use a simple button

File: src/ui/popup/manage-settings-page/style.less [hunk 6]
```diff
@@ -0,0 +1,31 @@
+@import "../../theme";
+
+.manage-settings-page {
+
+    &__button--active {
```
Comment (alexanderby) [inline src/ui/popup/manage-settings-page/style.less:5]: Is there a need in these rules? I think you can leave `.manage-settings-page {}` empty at the moment (it will be needed later).

File: src/ui/popup/settings-page/mange-settings-button.tsx [hunk 7]
```diff
@@ -0,0 +1,18 @@
...
+export default function ManageSettingsButton(props: {onClick: () => void}) {
+    return (
+        <ControlGroup>
+            <ControlGroup.Control>
+                <NavButton onClick={props.onClick}>
+                    Manage Settings
+                </NavButton>
+            </ControlGroup.Control>
+            <ControlGroup.Description>
+                Manage your current settings.
```
Comment (alexanderby) [inline src/ui/popup/settings-page/mange-settings-button.tsx:14]: The current description is too similar to button text, use `Reset, export or import settings`, dot is unnecessary

File: src/ui/popup/manage-settings-page/export-settings.tsx [hunk 8]
```diff
@@ -0,0 +1,21 @@
...
+        a.href = URL.createObjectURL(new Blob([data], {type: 'text/json'}));
+        a.download = 'DarkReader_Settings.json';
+        a.click();
+    }
+
+    return (
+        <Button
```
Comment (alexanderby) [inline src/ui/popup/manage-settings-page/export-settings.tsx:15]: Wrap `<Button>` into a `<ControlGroup>` and add description for those who don't understand what it does. Same for Import.

File: src/ui/popup/manage-settings-page/export-settings.tsx [hunk 9]
```diff
@@ -0,0 +1,26 @@
...
+            <ControlGroup.Control>
+                <Button 
+                    onclick={exportSettings}
+                    class="settings-button"
+                >
+                    Export Settings
+                </Button>
+            </ControlGroup.Control>
+            <ControlGroup.Description>
+                Export settings to a JSON file
```
Comment (alexanderby) [inline src/ui/popup/manage-settings-page/export-settings.tsx:22]: Replace word `Export` with `Save`

File: src/ui/popup/manage-settings-page/import-settings.tsx [hunk 10]
```diff
@@ -0,0 +1,36 @@
...
+import ControlGroup from '../control-group';
+import {UserSettings} from '../../../definitions';
+import {Button} from '../../controls';
+import {openFile} from '../../utils';
+
+export default function ImportButton(props: ViewProps) {
+    function importSettings() {
+        openFile({extensions: ['json']}, function (result: string) {
+            try {
+                const content: UserSettings = JSON.parse(result);
```
Comment (alexanderby) [inline src/ui/popup/manage-settings-page/import-settings.tsx:12]: Now, you have to add validation.

File: src/ui/popup/manage-settings-page/import-settings.tsx [hunk 11]
```diff
@@ -0,0 +1,36 @@
...
+            <ControlGroup.Control>
+                <Button 
+                    onclick={importSettings}
+                    class="settings-button"
+                >
+                    Import Settings
+                </Button>
+            </ControlGroup.Control>
+            <ControlGroup.Description>
+                Import settings from a JSON file
```
Comment (alexanderby) [inline src/ui/popup/manage-settings-page/import-settings.tsx:32]: Replace word `Import` with `Open`

File: src/ui/popup/manage-settings-page/style.less [hunk 12]
```diff
@@ -0,0 +1,3 @@
+.settings-button {
+    width: 100%
+}
```
Comment (alexanderby) [inline src/ui/popup/manage-settings-page/style.less:3]: Missing new line at the end of file

File: src/ui/popup/manage-settings-page/import-settings.tsx [hunk 13]
```diff
@@ -0,0 +1,71 @@
...
+                }
+            });
+        })(source, []);
+        return result;
+    }
+    function importSettings() {
+        openFile({extensions: ['json']}, function (result: string) {
+            try {
+                const content: UserSettings = JSON.parse(result);
+                const result2 = validate(content, flatten(DEFAULT_SETTINGS));
```
Comment (alexanderby) [inline src/ui/popup/manage-settings-page/import-settings.tsx:48]: I don't think it works:
```javascript
validate({a:10,x:20,c:{d:30}}, flatten({a:1,b:2,c:{d:3,e:4}}))
// -> {a: 10, d: 30}
```
Use algorithm that I explained.

File: src/ui/popup/manage-settings-page/import-settings.tsx [hunk 14]
```diff
@@ -0,0 +1,71 @@
...
+                props.actions.changeSettings({...result2});
+            } catch (err) {
+                console.log(err);
```
Comment (alexanderby) [inline src/ui/popup/manage-settings-page/import-settings.tsx:51]: use console.error for errors

File: src/ui/popup/manage-settings-page/style.less [hunk 15]
```diff
@@ -0,0 +1,3 @@
+.settings-button {
```
Comment (alexanderby) [inline src/ui/popup/manage-settings-page/style.less:1]: Does this stylesheet have effect?

File: src/ui/popup/manage-settings-page/import-settings.tsx (hunk 14 above)
Comment (Gusted) [reply src/ui/popup/manage-settings-page/import-settings.tsx:51]: Woops was for testing purposes.

File: src/ui/popup/manage-settings-page/import-settings.tsx [hunk 16]
```diff
@@ -0,0 +1,62 @@
...
+import {DEFAULT_SETTINGS} from '../../../defaults';
+import {forEach} from '../../../utils/array';
+
+export default function ImportButton(props: ViewProps) {
+
+    function getValidatedObject(source: any, compare: any) {
+        const result = {};
+        forEach(Object.keys(source), (key) => {
+            const value: string = source[key];
+            const array1: boolean = Array.isArray(value)
```
Comment (alexanderby) [inline src/ui/popup/manage-settings-page/import-settings.tsx:16]: Array.isArray(value) returns a boolean, no need to explicitly specify the type

File: src/ui/popup/manage-settings-page/import-settings.tsx [hunk 17]
```diff
@@ -0,0 +1,62 @@
...
+            const array2: boolean = Array.isArray(compare[key])
+            if (value == null || compare[key] == null) {
+                return;
+            }
+            if (array1 || array2) {
+                if (array1 && array2) {
+                    result[key] = value;
+                }
+            } else if (typeof value === 'object') {
+                result[key] = getValidatedObject(value, compare[key]);
```
Comment (alexanderby) [inline src/ui/popup/manage-settings-page/import-settings.tsx:26]: Bug, try this:
```javascript
getValidatedObject(
  {a: {b: 1}},
  {a: 2},
);
```

File: src/ui/popup/manage-settings-page/import-settings.tsx [hunk 18]
```diff
@@ -0,0 +1,62 @@
...
+export default function ImportButton(props: ViewProps) {
+
+    function getValidatedObject(source: any, compare: any) {
+        const result = {};
+        forEach(Object.keys(source), (key) => {
+            const value: string = source[key];
+            const array1: boolean = Array.isArray(value)
+            const array2: boolean = Array.isArray(compare[key])
+            if (value == null || compare[key] == null) {
+                return;
```
Comment (alexanderby) [inline src/ui/popup/manage-settings-page/import-settings.tsx:19]: So, `array1` and `array2` become useless here, so move this condition to the beginning.

File: src/ui/popup/manage-settings-page/import-settings.tsx [hunk 19]
```diff
@@ -0,0 +1,62 @@
...
+import {UserSettings} from '../../../definitions';
+import {Button} from '../../controls';
+import {openFile} from '../../utils';
+import {DEFAULT_SETTINGS} from '../../../defaults';
+import {forEach} from '../../../utils/array';
+
+export default function ImportButton(props: ViewProps) {
+
+    function getValidatedObject(source: any, compare: any) {
+        const result = {};
```
[the remark this answers is not in the document]
Comment (Gusted) [reply src/ui/popup/manage-settings-page/import-settings.tsx:13]: Why empty? It can contains objects in itself

File: src/ui/popup/manage-settings-page/import-settings.tsx [hunk 20]
```diff
@@ -0,0 +1,64 @@
...
+import {UserSettings} from '../../../definitions';
+import {Button} from '../../controls';
+import {openFile} from '../../utils';
+import {DEFAULT_SETTINGS} from '../../../defaults';
+
+export default function ImportButton(props: ViewProps) {
+
+    function getValidatedObject<T>(source: any, compare: T): Partial<T>  {
+        const result = {};
+        if (source == null || (typeof source !== 'object' && !Array.isArray(source))) {
```
Comment (alexanderby) [inline src/ui/popup/manage-settings-page/import-settings.tsx:13]: Use `source == null || typeof source !== 'object' || Array.isArray(source)` so that only plain objects pass.
