### PR TITLE
Fix: work around Vivaldi erroneously injecting CS into panes

### LINKED ISSUE #6842: [Bug] Sidebar pages in Vivaldi browser get broken dark theme
# Bug Report

## Bug Description

All pages in the sidebar in the Vivaldi browser get some kind of partial dark theme. (Probably since last update?)

## Website Address

Any, but it must be in the sidebar in the Vivaldi

## Steps To Reproduce

- Launch Vivaldi
- Install Dark Reader
- (optionally) set Dark Reader to "Disabled on all websites by default"
- Add any page to sidebar panel (e.g. Instagram, Duolingo...) 

## Expected Behavior

I'd expect Dark Reader to not work in the sidebar at all since extensions (like uBlock etc.) usually don't work there. And it didn't work there until today. But if it does work, it should display websites correctly and also adhere to Dark Reader settings.

## Actual Behavior

Websites get dark background, white text, but lot of images are missing (on Instagram and Duolingo). I also changed DR settings to "Disabled on all websites by default" and even non-whitelisted pages in the sidebar have this broken dark theme anyway.

## Screenshots

Duolingo missing all the icons for the lessons.
Duolingo

## System Information

- OS: Windows 10 Pro 20H2 64-bit
- Browser: latest Vivaldi 4.2.2406.48 64-bit
- Dark Reader Version: 4.9.35

## Additional Context

I didn't have this issue today morning. I suppose the extension got updated and now I can't use pages in sidebar.
According to DevTools, pages in the sidebar have this (at least) one element from Dark Reader extension injected:
`<style class="darkreader darkreader--fallback" media="screen">html, body, body :not(iframe):not(div[style^="position:absolute;top:0;left:-"]) { background-color: #181a1b !important; border-color: #776e62 !important; color: #e8e6e3 !important; } html, body { opacity: 1 !important; transition: none !important; }</style>`
Deleting this element manually in DevTools fixes the problem, until next page load, obviously.

I can also see this log in the Console of the Dark Reader extension, not sure if it's relevant to the issue:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'id')
    at reply (index.js:2843)
    at index.js:2853
```

### PR DESCRIPTION
**Pull request by bershanskiy**
Fixes #6842.

Vivaldi can display pages in a "sidebar" and sometimes erroneously injects CS into them, but does not handle messaging properly. This causes a Dark Reader to inject partial styles and break the page. This bug has been observed since [2017](https://forum.vivaldi.net/topic/16098/some-extensions-are-not-working-in-web-panels), but started affecting Dark Reader only [recently](https://forum.vivaldi.net/topic/50265/dark-reader-effects-web-panels-uncontrollably).

@mateuszkozakiewicz If you have time, please run this more complete manual testing:
1. Delete or disable all versions of Dark Reader
2. [Download](https://github.com/darkreader/darkreader/releases/download/v4.9.36/darkreader-chrome.zip) and install from source v4.9.36. Open a pane (it should be messed up)
3. Remove v4.9.36
4. [Download](https://github.com/bershanskiy/darkreader/actions/runs/1260859038) and install from source new version. Open pane (it should be fine).

This more holistic test plan verifies that it's the patch fixing the bug and not some other random factor (like installing from source).

### CODE REVIEW

**Comment by mateuszkozakiewicz** [comment]
I can confirm that it is working as you explained:

> 2\. [Download](https://github.com/darkreader/darkreader/releases/download/v4.9.36/darkreader-chrome.zip) and install from source v4.9.36. Open a pane (it should be messed up)

This one causes side panels to have broken styles with the following error:
image

> 4\. [Download](https://github.com/bershanskiy/darkreader/actions/runs/1260859038) and install from source new version. Open pane (it should be fine).

This one is not doing anything to side panels, normal tabs are working as expected.

**Comment by bershanskiy** [comment]
@Gusted This is ready for review.

File: src/inject/index.ts [hunk 1]
```diff
@@ -33,7 +33,15 @@ function sendMessage(message: Message) {
         return;
     }
     try {
-        chrome.runtime.sendMessage<Message>(message);
+        chrome.runtime.sendMessage<Message>(message, (response) => {
```
Comment (Gusted) [inline src/inject/index.ts:36]: Kinda sketchy but seems like a good change.

**Review by Gusted — APPROVED** [review]
And off we go.
