### PR TITLE
Make lazy-loaded elements manage-able

### LINKED ISSUE #2729: [Broken Website] songsear.ch doesn't darken on page load?
songsear.ch

**How to Reproduce**
An example for this is
> 1. Go to the website
> 2. No dark backgrounds, fully white.
> 3. Enable and then disable the darkness and it works again.

This is the first website I actively go to which has had this problem for me.

**Expected behavior**
Darkness to be there on pageload. 

**Actual behavior**
No dark background on pageload.

Image of Yaktocat

**System info:**
 - OS: W10
 - Browser Chrome

### LINKED ISSUE #3649: [Broken Website] Techspot comments on Fenix Nightly going white
**Website**
https://www.techspot.com/news/86788-mozilla-needs-help-figure-out-youtube-recommendation-algorithms.html

**How to Reproduce**
1. Go to any article on Techspot 
2. Scroll down, and press on open comments
3. All the comments are white until you open dark reader settings to disable and renable it for techspot.com

**Expected behavior**
Dark background with white text

**Actual behavior**
White background with white text

**Screenshots**
Screenshot_2020-09-16-01-47-40-60

**System info:**
 - OS: Android
 - Browser: Firefox Nightly 200914 06:05
 - Darkreader Version: 4.9.19
 
**Additional context**

### PR DESCRIPTION
**Pull request by Gusted**
- Adds a extra attribute to watch for. `media` attribute is changed when it's finished 'lazy-loading'.
- Resolves #3649
- Resolves #2729

### CODE REVIEW

File: src/inject/dynamic-theme/style-manager.ts [hunk 1]
```diff
@@ -53,7 +53,11 @@ export function shouldManageStyle(element: Node) {
             )
         ) &&
         !element.classList.contains('darkreader') &&
-        element.media !== 'print' &&
+        (
+            element.media !== 'print' ||
+            // Some stylesheets uses 'lazy loading' and has on initial a `print` media.
+            element.getAttribute('onload').toLowerCase().includes('this.media=')
```
Comment (alexanderby) [inline src/inject/dynamic-theme/style-manager.ts:59]: Ehmm, looks like a hack. Is it a common problem for these websites? Why do they do this? Like the styles are not shown until they finish loading? I thought the browser optimizes it. Maybe it fixes the problem for some IE.

Let's find out if there's a less hacky way. E.g. watching for media attribute change should have worked. [Here](https://github.com/darkreader/darkreader/blob/master/src/inject/dynamic-theme/watch.ts#L165) it is triggered on attribute change and when the condition fulfills (style becomes manageable when media is no longer "print"), it should process it. Try finding out what's the problem. Maybe changes of media through JS are not reflected in attribute value.

**Review by alexanderby — CHANGES_REQUESTED** [review]

File: src/inject/dynamic-theme/style-manager.ts (hunk 1 above)
Comment (Gusted) [reply src/inject/dynamic-theme/style-manager.ts:59]: > Ehmm, looks like a hack. Is it a common problem for these websites? Why do they do this? Like the styles are not shown until they finish loading? I thought the browser optimizes it. Maybe it fixes the problem for some IE.

https://github.com/darkreader/darkreader/issues/2729#issuecomment-640201661
https://css-tricks.com/the-simplest-way-to-load-css-asynchronously/
It's probably to improve FCP(First contenfull Paint) aka Eliminate Render-Blocking Resources to speed it up, it's one of the ways to do this.

> Let's find out if there's a less hacky way. E.g. watching for media attribute change should have worked. Here it is triggered on attribute change and when the condition fulfills (style becomes manageable when media is no longer "print"), it should process it. Try finding out what's the problem. Maybe changes of media through JS are not reflected in attribute value.

I'm not sure if we have a mutation observer on non-manage-able `elements` e.g. links, that's another workaround like you suggested.

**Review by alexanderby — APPROVED** [review]
That's it!
