### PR TITLE
Pre-Release and fixing bugs

### LINKED ISSUE #2660: [BUG] Toggle status is ignored if query string contains square braces
**Describe the bug**
If you navigate to a page you have disabled DarkReader for (via the toggle) and the URI for that page contains a `[` (in the query string) then the rule you have set will be ignored.  
When the braces are encoded this issue does not occur.

**To Reproduce**
1. Navigate to `google.co.uk`
1. Disable DarkReader via the quick toggle
1. Notice DarkReader isn't applied
1. Navigate to `google.co.uk?foo=[bar]`
1. Notice DarkReader is applied

**Expected behavior**
DarkReader should not be applied when it is toggled off

**Screenshots**
image
image

**System Information:**
 - MacOS 10.15.4
 - Chrome 83.0.4103.61

**Additional context**
Note: Between my first and second screenshot, DarkReader was **not** toggle manually

### PR DESCRIPTION
**Pull request by Gusted**
- Resolves #2660

### CODE REVIEW

File: src/utils/url.ts [hunk 1]
```diff
@@ -31,9 +31,14 @@ export function isURLInList(url: string, list: string[]) {
 export function isURLMatched(url: string, urlTemplate: string): boolean {
     const isFirstIPV6 = url.includes('[');
```
Comment (alexanderby) [inline src/utils/url.ts:32]: `isFirstIPV6` and `isSecondIPV6` should be true, if they are IPv6. So, create a `function isIPv6(url: string): boolean`, other code should stay the same.

File: tests/url.tests.ts [hunk 2]
```diff
@@ -167,6 +167,14 @@ test('URL is enabled', () => {
         {isProtected: false, isInDarkList: true},
     )).toEqual(false);
 
+    // Because some people who don't know about XSS still don't encode their URL's and have vulnerable [] in them sigh.
```
Comment (alexanderby) [inline tests/url.tests.ts:170]: Shorten this comment just to note that unescaped `[]` can appear in URL query.
