### PR TITLE
Should add root variable after type is discovered

### LINKED ISSUE #6215: [Broken Website] https://outlook.live.com/owa/
# Broken Website
## Website
https://outlook.live.com/owa/ (This URL is the homepage for the site.)
https://outlook.live.com/mail/0/inbox (This URL is the one displayed once signed in to the site.)

## How to Reproduce
1. Visit the site. (See screenshots for the original and the Dark Reader versions of the site.)
2. Create account / Use existing account.
3. Sign in.

## Expected behavior
The site displays correctly when using Dark Reader.

## Actual behavior
The site displays black text on a dark background when using Dark Reader.

## Screenshots
Original:

outlook com-DR-disabled

Dark Reader:

outlook com-DR-enabled

## System Information

- OS: Windows 10 21H1 (19043.1083)
- Browser: Firefox Nightly 91.0a1 (20210708091856)
- Dark Reader Version: 4.9.34

## Additional context
N/A

### PR DESCRIPTION
**Pull request by Gusted**
- Resolves #6215
- Imagine a scenario whereby the root variable aren't yet discovered. But at a later stage they are, with this patch that should result in a rebuild of the root variables and actually include the new found variable with the correct type.

### CODE REVIEW

File: src/inject/dynamic-theme/variables.ts [hunk 1]
```diff
@@ -310,7 +311,10 @@ export class VariablesStore {
         if (!this.typeChangeSubscriptions.has(varName)) {
             this.typeChangeSubscriptions.set(varName, new Set());
         }
-        this.typeChangeSubscriptions.get(varName).add(callback);
+        const rootStore = this.typeChangeSubscriptions.get(varName);
+        if (!rootStore.has(callback)) {
```
Comment (Gusted) [inline src/inject/dynamic-theme/variables.ts:315]: I'm not sure if this is the best way, but this should prevent multiple "same" callback being added to the subscriptions.

**Review by alexanderby — APPROVED** [review]
