### PR TITLE
Filter fix

### LINKED ISSUE #2256: Filter(+) theme suddenly not working for some websites
I am not sure if this is a specific problem of my own or common to everyone.

Here are the following websites I have problems suddenly 2 days ago with Darkreader;
https://www.wsj.com/
https://fortune.com/
https://www.ft.com/

### PR DESCRIPTION
**Pull request by Gusted**
As of the chromium version `81.0.4035.0` 
To comfirm yourself [this](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/733497/) Version is for windows 64 bit to download `81.0.4034.0` where the patch was not into the source code of chromium,
[The issue](https://bugs.chromium.org/p/chromium/issues/detail?id=501582)
[The fix that has been made in chromium](https://chromium-review.googlesource.com/c/chromium/src/+/1979258)

Some major credits to @alexanderby To pointing out the issue and letting me know setting the background-color to white should fix this issue. (@sierratango88 Pointing this also) I should pay closer attention to comments next time...

Closes #2256

### CODE REVIEW

**Comment by Gusted** [comment]
[darkreader.zip](https://github.com/darkreader/darkreader/files/4494531/darkreader.zip)
For everyone that really want to use Filter theme right now this is a compiled version you will need to sideload it. **I DO NOT RECOMMEND USING THIS UNLESS YOU KNOW WHAT YOU ARE DOING**

**Comment by erockce** [comment]
@Gusted, thank you for saving my eyes! FWIW, confirmed it works on `Ubuntu 18.04.4 LTS` with` Google Chrome `Version 81.0.4044.113 (Official Build) (64-bit)`. Now I don't have to go create custom settings for my most frequented sites, that I would have to revert back once a new Dark Reader version would be released.

**Comment by Gusted** [comment]
> @Gusted, thank you for saving my eyes! FWIW, confirmed it works on `Ubuntu 18.04.4 LTS` with` Google Chrome `Version 81.0.4044.113 (Official Build) (64-bit)`. Now I don't have to go create custom settings for my most frequented sites, that I would have to revert back once a new Dark Reader version would be released.


Haha thank you!

File: src/generators/css-filter.ts [hunk 1]
```diff
@@ -5,12 +5,22 @@ import {parseArray, formatArray} from '../utils/text';
 import {compareURLPatterns, isURLInList} from '../utils/url';
 import {createTextStyle} from './text-style';
 import {FilterConfig, InversionFix} from '../definitions';
+import { compareChromeVersions, getChromeVersion, isChrome } from '../utils/platform';
```
Comment (alexanderby) [inline src/generators/css-filter.ts:8]: The current code style don't have spaces between braces.

File: src/generators/css-filter.ts [hunk 2]
```diff
@@ -5,12 +5,22 @@ import {parseArray, formatArray} from '../utils/text';
...
 
 export enum FilterMode {
     light = 0,
     dark = 1
 }
 
+export function hasRootIssue() {
```
Comment (alexanderby) [inline src/generators/css-filter.ts:15]: We both know about the issue, but let's name this function so that it makes sense for those who not. But not too long. Also you can add a link to the Chromium issue in comment.

File: src/generators/css-filter.ts [hunk 3]
```diff
@@ -5,12 +5,22 @@ import {parseArray, formatArray} from '../utils/text';
...
+    const chromeVersion = getChromeVersion();
+    return Boolean(
+        chromeVersion &&
+        isChrome() &&
+        compareChromeVersions(chromeVersion, "81.0.4035.0") >= 0
+    )
```
Comment (alexanderby) [inline src/generators/css-filter.ts:21]: I guess that `npm run code-style` didn't work for some reason. Maybe file patterns didn't work on Windows because of `/` in paths, or maybe single quotes should be replaced with `\"`.

File: src/utils/platform.ts [hunk 4]
```diff
@@ -1,3 +1,7 @@
+export function isChrome() {
+    return navigator.userAgent.includes('Chrome');
```
Comment (alexanderby) [inline src/utils/platform.ts:2]: It should also work for Chromium browsers. See `getChromeVersion` function.

File: src/generators/css-filter.ts [hunk 5]
```diff
@@ -63,7 +73,10 @@ export function cssFilterStyleheetTemplate(filterValue: string, reverseFilterVal
     });
 
     if (!frameURL) {
-        const [r, g, b] = applyColorMatrix([255, 255, 255], createFilterMatrix(config));
+        let [r, g, b] = applyColorMatrix([255, 255, 255], createFilterMatrix(config));
+        if (hasRootIssue()) {
+            [r, g, b] = applyColorMatrix([0, 0, 0], createFilterMatrix(config));
```
Comment (alexanderby) [inline src/generators/css-filter.ts:78]: As far as I understand, for Light mode it should be `[255. 255, 255]`.

File: src/generators/css-filter.ts (hunk 3 above)
Comment (Gusted) [reply src/generators/css-filter.ts:21]: I will look into that

File: src/generators/css-filter.ts (hunk 5 above)
Comment (Gusted) [reply src/generators/css-filter.ts:78]: This way worked for me is it has the rootIssue and set it to 0,0,0

File: src/utils/platform.ts (hunk 4 above)
Comment (Gusted) [reply src/utils/platform.ts:2]: It works for chromium browser Google have turned Chromium almost into chrome don't worry

File: src/generators/css-filter.ts [hunk 6]
```diff
@@ -5,12 +5,22 @@ import {parseArray, formatArray} from '../utils/text';
...
 import {createTextStyle} from './text-style';
 import {FilterConfig, InversionFix} from '../definitions';
+import {compareChromeVersions, getChromeVersion, isChromiumBased} from '../utils/platform';
 
 export enum FilterMode {
     light = 0,
     dark = 1
 }
 
+export function hasNewBehaviorRootElements() { // https://chromium-review.googlesource.com/c/chromium/src/+/1979258 & https://bugs.chromium.org/p/chromium/issues/detail?id=501582
```
Comment (alexanderby) [inline src/generators/css-filter.ts:15]: The `new behavior` can become old some day. And other browsers are not affected. If you will have no ideas, how to give a descriptive name, about what is the behavior, let's name it like `hasChromiumIssue501582`.

Also, let's put a comment on a separate line using `// link` or `/**\n * link\n */`.

File: src/generators/css-filter.ts [hunk 7]
```diff
@@ -5,11 +5,24 @@ import {parseArray, formatArray} from '../utils/text';
...
 }
+/**
+* Bug report:  https://bugs.chromium.org/p/chromium/issues/detail?id=501582
+* Patch: https://chromium-review.googlesource.com/c/chromium/src/+/1979258
+*/
+export function hasChromiumIssue501582() { 
+    const chromeVersion = getChromeVersion();
+    return Boolean(
+        chromeVersion &&
+        isChromiumBased() &&
```
Comment (alexanderby) [inline src/generators/css-filter.ts:22]: if `chromeVersion` is null, then there is no need to call this function.

File: src/generators/css-filter.ts [hunk 8]
```diff
@@ -5,11 +5,24 @@ import {parseArray, formatArray} from '../utils/text';
...
 import {createTextStyle} from './text-style';
 import {FilterConfig, InversionFix} from '../definitions';
+import {compareChromeVersions, getChromeVersion, isChromiumBased} from '../utils/platform';
 
 export enum FilterMode {
     light = 0,
     dark = 1
 }
+/**
+* Bug report:  https://bugs.chromium.org/p/chromium/issues/detail?id=501582
```
Comment (alexanderby) [inline src/generators/css-filter.ts:15]: Use single space on the next line of JSDoc comment.

File: src/generators/css-filter.ts [hunk 9]
```diff
@@ -63,7 +76,10 @@ export function cssFilterStyleheetTemplate(filterValue: string, reverseFilterVal
     });
 
     if (!frameURL) {
-        const [r, g, b] = applyColorMatrix([255, 255, 255], createFilterMatrix(config));
+        let [r, g, b] = applyColorMatrix([255, 255, 255], createFilterMatrix(config));
```
Comment (alexanderby) [inline src/generators/css-filter.ts:79]: `createFilterMatrix(config)` is called twice. `applyColorMatrix` is also called twice for users of Chrome >=81 (who are now majority). So maybe let's use `if` ... `else`.

File: src/generators/css-filter.ts (hunk 7 above)
Comment (Gusted) [reply src/generators/css-filter.ts:22]: This?

Comment (Gusted) [reply src/generators/css-filter.ts:21]: Check line 81

File: src/generators/css-filter.ts [hunk 10]
```diff
@@ -5,11 +5,23 @@ import {parseArray, formatArray} from '../utils/text';
...
 import {createTextStyle} from './text-style';
 import {FilterConfig, InversionFix} from '../definitions';
+import {compareChromeVersions, getChromeVersion, isChromiumBased} from '../utils/platform';
 
 export enum FilterMode {
     light = 0,
     dark = 1
 }
+/**
+* Bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=501582
```
Comment (alexanderby) [inline src/generators/css-filter.ts:15]: It should look like:
```
/**
 * Text here
 */

One extra space on new line.

File: src/generators/css-filter.ts [hunk 11]
```diff
@@ -5,11 +5,23 @@ import {parseArray, formatArray} from '../utils/text';
...
+* Patch: https://chromium-review.googlesource.com/c/chromium/src/+/1979258
+*/
```
Comment (alexanderby) [inline src/generators/css-filter.ts:18]: And this line should start with empty space

File: src/generators/css-filter.ts [hunk 12]
```diff
@@ -63,7 +75,16 @@ export function cssFilterStyleheetTemplate(filterValue: string, reverseFilterVal
     });
 
     if (!frameURL) {
-        const [r, g, b] = applyColorMatrix([255, 255, 255], createFilterMatrix(config));
+        let r: number;
+        let g: number;
+        let b: number;
+        if (getChromeVersion() == null){
+            [r,g,b] = applyColorMatrix([255, 255, 255], createFilterMatrix(config));
```
Comment (alexanderby) [inline src/generators/css-filter.ts:84]: Something is wrong with spacing: `[r,g,b]` should be `[r, g, b]`.

File: src/generators/css-filter.ts [hunk 13]
```diff
@@ -63,7 +75,16 @@ export function cssFilterStyleheetTemplate(filterValue: string, reverseFilterVal
...
+        }else if (hasChromiumIssue501582()) {
+            [r,g,b] = applyColorMatrix([0, 0, 0], createFilterMatrix(config));
```
Comment (alexanderby) [inline src/generators/css-filter.ts:86]: `createFilterMatrix(config)` could be moved to another variable (cause it is called twice in two code branches).

File: src/generators/css-filter.ts (hunk 5 above)
Comment (Gusted) [reply src/generators/css-filter.ts]: I Would test it 1 more time

File: src/generators/css-filter.ts [hunk 14]
```diff
@@ -63,7 +77,16 @@ export function cssFilterStyleheetTemplate(filterValue: string, reverseFilterVal
     });
 
     if (!frameURL) {
-        const [r, g, b] = applyColorMatrix([255, 255, 255], createFilterMatrix(config));
+        let r: number;
+        let g: number;
+        let b: number;
+        if (getChromeVersion() == null){
```
Comment (alexanderby) [inline src/generators/css-filter.ts:83]: The same thing is called twice (in `if` and `else` blocks). Make it called once. Also, only the array is different in all 3 blocks. So we can shorten it like `const [r, g, b] = hasIssue() ? [x] : [y];`

File: src/generators/css-filter.ts (hunk 13 above)
Comment (Gusted) [reply src/generators/css-filter.ts:86]: Explain please?

File: src/generators/css-filter.ts (hunk 14 above)
Comment (Gusted) [reply src/generators/css-filter.ts:83]: I don't get what you try to mean

File: src/generators/css-filter.ts (hunk 11 above)
Comment (Gusted) [reply src/generators/css-filter.ts:18]: It already starts with an empty space?

Comment (alexanderby) [reply src/generators/css-filter.ts:18]: My fault, it should start with single space. Compare:
```
/**
 * Correct
 */
```
```
/**
* Wrong
*/
```

File: src/generators/css-filter.ts [hunk 15]
```diff
@@ -63,7 +76,7 @@ export function cssFilterStyleheetTemplate(filterValue: string, reverseFilterVal
     });
 
     if (!frameURL) {
-        const [r, g, b] = applyColorMatrix([255, 255, 255], createFilterMatrix(config));
+        let [r, g, b] = hasChromiumIssue501582() ? [0, 0, 0] : [255, 255, 255];
```
Comment (alexanderby) [inline src/generators/css-filter.ts:79]: Use `const` since it is never changed. But ESLint should have generate a warning for that.

File: src/generators/css-filter.ts [hunk 16]
```diff
@@ -5,12 +5,25 @@ import {parseArray, formatArray} from '../utils/text';
...
 
 export enum FilterMode {
     light = 0,
     dark = 1
 }
 
+/**
+ * Bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=501582
+ * Patch: https://chromium-review.googlesource.com/c/chromium/src/+/1979258
+*/
```
Comment (alexanderby) [inline src/generators/css-filter.ts:18]: Missing white space.

**Comment by alexanderby** [comment]
I will check how it works, just a moment.

File: src/generators/css-filter.ts (hunk 16 above)
Comment (Gusted) [reply src/generators/css-filter.ts:18]: Where?

File: src/generators/css-filter.ts [hunk 17]
```diff
@@ -63,7 +76,7 @@ export function cssFilterStyleheetTemplate(filterValue: string, reverseFilterVal
     });
 
     if (!frameURL) {
-        const [r, g, b] = applyColorMatrix([255, 255, 255], createFilterMatrix(config));
+        const [r, g, b] = hasChromiumIssue501582() ? applyColorMatrix([0, 0, 0], createFilterMatrix(config)) :applyColorMatrix([255, 255, 255], createFilterMatrix(config));
```
Comment (alexanderby) [inline src/generators/css-filter.ts:79]: Let's make code more clear. Make `applyColorMatrix` be called only once. Move array and filter matrix into separate variables.

File: src/generators/css-filter.ts [hunk 18]
```diff
@@ -63,7 +76,8 @@ export function cssFilterStyleheetTemplate(filterValue: string, reverseFilterVal
     });
 
     if (!frameURL) {
-        const [r, g, b] = applyColorMatrix([255, 255, 255], createFilterMatrix(config));
+        const [x, y, z] = hasChromiumIssue501582() ? [0, 0, 0] : [255, 255, 255];
```
Comment (alexanderby) [inline src/generators/css-filter.ts:79]: Well, `[x, y, z]` looks not clear. Also you are destructuring an array into parts, and later put these parts into another array. Could you please use a variable with a name explaining what is `[0, 0, 0]` or `[255, 255, 255]`?

**Comment by alexanderby** [comment]
Looks good, now I will check it in different browsers.

**Comment by alexanderby** [comment]
Just imagine that you are a person who sees your code for the first time and try to ask yourself questions like "what it is doing". Leave comments when it is not possible to name functions and variables.

**Comment by Gusted** [comment]
> Just imagine that you are a person who sees your code for the first time and try to ask yourself questions like "what it is doing". Leave comments when it is not possible to name functions and variables.

This the best I came up with

**Comment by alexanderby** [comment]
I meant not this PR, but just that `function issue123() {} ` is better than `/* issue 123 */function issue() {}`.

Now, there is an error. It works wrong in Light mode. You have to look for `config.mode` property. 1 is for dark and 0 for light. Later this will be renamed into `config.scheme: 'dark' | 'light'`.

**Comment by Gusted** [comment]
> I meant not this PR, but just that `function issue123() {} ` is better than `/* issue 123 */function issue() {}`. You've already left a link to Chromium issue. But let it be.
> 
> Now, there is an error. It works wrong in Light mode. You have to look for `config.mode` property. 1 is for dark and 0 for light. Later this will be renamed into `config.scheme: 'dark' | 'light'`.

So whens it's light it should be [255, 255, 255] Again?

**Comment by alexanderby** [comment]
Yes. Here we go again.
cj

**Comment by Gusted** [comment]
> Yes. Here we go again.
> cj

Oh bruh are we trying to meme on github 😅

File: src/generators/css-filter.ts [hunk 19]
```diff
@@ -63,7 +77,9 @@ export function cssFilterStyleheetTemplate(filterValue: string, reverseFilterVal
     });
 
     if (!frameURL) {
-        const [r, g, b] = applyColorMatrix([255, 255, 255], createFilterMatrix(config));
+        // If user has the chrome issue the colors should be the other way around as of the rootcolors will affect the whole background color of the page
+        const rootColors = hasChromiumIssue501582(config) ? [0, 0, 0] : [255, 255, 255];
```
Comment (alexanderby) [inline src/generators/css-filter.ts:81]: Config has no relation to Chromium issue.

Comment (Gusted) [reply src/generators/css-filter.ts:81]: It's required to check if the config is light or dark don't want to make more in this function

Comment (alexanderby) [reply src/generators/css-filter.ts]: `hasChromiumIssue501582` should only say, is there Chromium issue or not. But it's great you don't want a mess in `cssFilterStyleheetTemplate`, it is already messy. You can create a `getDefaultRootColor(config)` function.

Comment (Gusted) [reply src/generators/css-filter.ts]: Refresh for the newest commit :)

File: src/generators/css-filter.ts [hunk 20]
```diff
@@ -63,7 +79,9 @@ export function cssFilterStyleheetTemplate(filterValue: string, reverseFilterVal
     });
 
     if (!frameURL) {
-        const [r, g, b] = applyColorMatrix([255, 255, 255], createFilterMatrix(config));
+        // If user has the chrome issue the colors should be the other way around as of the rootcolors will affect the whole background color of the page
+        const rootColors = hasChromiumIssue501582() && config.mode === FilterMode.light ? [0, 0, 0] : [255, 255, 255];
```
Comment (alexanderby) [inline src/generators/css-filter.ts:83]: I created a table to help understand, what value should be.
```
             | dark mode                       | light mode
not Chrome   | [0, 0, 0] remains [0, 0, 0]     | [255, 255, 255] remains [255, 255, 255]
old Chrome   | [0, 0, 0] remains [0, 0, 0]     | [255, 255, 255] remains [255, 255, 255]
issue 501582 | [255, 255, 255] turns [0, 0, 0] | [255, 255, 255] should remain [255, 255, 255]
```

Use `config.mode === FilterMode.dark`. I think it will be the final.

Comment (alexanderby) [reply src/generators/css-filter.ts:83]: Our problem is there are no unit tests. We could just create some test samples and quickly find errors like this. Maybe we will do it later.

Comment (Gusted) [reply src/generators/css-filter.ts]: Later please just say this works and I can Squash those commits

**Comment by alexanderby** [comment]
Just to make you laugh, take a look here https://github.com/darkreader/darkreader/blob/v3.5.4/src/background/filter_css_generator.ts#L57

**Comment by Gusted** [comment]
....... I'm moving back to fixing CSS issues

**Comment by alexanderby** [comment]
respect
