### PR TITLE
Throttle Inline attribute

### LINKED ISSUE #1222: Conflict with the plugin Pinterest Save Button
When I turn on Dark Reader, it will result in Pinterest Save Button failing to work.

### LINKED ISSUE #3864: [Broken Website] How to solve this from happening?
**Website**
https://app.smarttask.io 

**How to Reproduce**
- Go to calendar or board view

**Expected behavior**
- I guess there should be able to avoid so much processing that it just crashes. 

**Actual behavior**
Crashes the browser tab

- Latest version

### PR DESCRIPTION
**Pull request by Gusted**
- Max trottle the inline attribute changer to 50 attributes in 10 seconds.
- Should partially resolve conflicts with certain elements that intend to revert our changes to a element.
- Resolves #3864
- Resolves #1222

### CODE REVIEW

File: src/inject/dynamic-theme/inline-style.ts [hunk 1]
```diff
@@ -168,7 +170,14 @@ function deepWatchForInlineStyles(
     });
     treeObservers.set(root, treeObserver);
 
-    const attrObserver = new MutationObserver((mutations) => {
+    let attributecount = 0;
```
Comment (alexanderby) [inline src/inject/dynamic-theme/inline-style.ts:173]: Rename this variable to have a proper meaning. Is it attempts count> Use camel case.

File: src/inject/dynamic-theme/inline-style.ts [hunk 2]
```diff
@@ -178,6 +187,31 @@ function deepWatchForInlineStyles(
...
+        if (start == null) {
+            start = now;
+        } else if (attributecount >= MAX_ATTEMPTS_COUNT) {
+            if (now - start < ATTEMPTS_INTERVAL) {
+                timeoutId = setTimeout(() => {
+                    start = null;
+                    attributecount = 0;
+                    timeoutId = null;
+                    handleAttributionMutations(cache);
+                }, 2000);
```
Comment (alexanderby) [inline src/inject/dynamic-theme/inline-style.ts:206]: Move `2000` into a constant too.

**Review by alexanderby — CHANGES_REQUESTED** [review]
