### PR TITLE
Fix: on Firefox, register commands in setTimeout()

### LINKED ISSUE #10176: [Bug]  Alt+Shift+D No Longer works in Firefox/Librewolf
# Bug Report
## Bug Description
I use this extension on a daily basis and was surprised when the Alt+Shift+D keyboard shortcut for toggling Dark Reader no longer worked. I double checked that my keyboard was sending the proper keystrokes using screenkey and other applications and also double checked that Dark Reader worked as expected on Brave (it did).  This issue is unique to my Firefox Fork, Librewolf as far as I know. I also downloaded the standard Firefox to test and it also suffered from the same problem (Librewolf Firefox version 105.0.1, Firefox version 106.0.1-1).
## Expected Behavior

Expected Behavior was for Dark Reader to Toggle the Dark/Light settings of the website I was on (DuckDuckGo) when I invoked the Alt+Shift+D keyboard command.
## Actual Behavior

Dark Reader did NOT Toggle the Dark/Light settings when invoking the Alt+Shift+D keyboard command.

## System Information
My Browser is Librewolf Firefox (105.0.1). The Same Bug was observed on standard Firefox (106.0.1). Dark Reader version is 4.9.59.

- OS: Linux
- Browser: Librewolf Firefox 105.0.1 and Firefox 106.0.1 (also tested in Brave 105.1.43.93, bug does not occur in Brave browser)
- Dark Reader Version: 4.9.59

## Additional Context

I have made sure to double check my keyboard itself, along with turning off other extensions that might affect this (Vimium). My keyboard is functioning as expected, with the Alt and Shift and D keys working as expected in other appliications. Turning Vimium off did not resolve the issue.

### PR DESCRIPTION
**Pull request by bershanskiy**
Fixes #10176.

Firefox for some reason silently failed to register context menus via `chrome.commands.onCommand.addListener` on the first run, so we need to wrap it into `setTimeout()` (with no delay).

### CODE REVIEW

File: src/background/extension.ts [hunk 1]
```diff
@@ -92,7 +92,12 @@ export class Extension {
 
         if (chrome.commands) {
             // Firefox Android does not support chrome.commands
-            chrome.commands.onCommand.addListener(async (command, {id: tabId}) => this.onCommand(command as Command, tabId, 0, undefined));
+            if (isFirefox) {
+                // Firefox may not register onCommand listener on extension startup so we need to use setTimeout
+                setTimeout(() => chrome.commands.onCommand.addListener(async (command) => this.onCommand(command as Command, null, null, null)));
```
Comment (bershanskiy) [inline src/background/extension.ts:97]: This is the actual fix for #10176, the rest is just minor style changes/nits/etc.
