### PR TITLE
Modify variables to match theme settings

### LINKED ISSUE #4182: [Broken Website] Github has grey colors
**Website**
https://github.com

**How to Reproduce**

Visit any repository.

**Expected behavior**

Before, GitHub was dark as it should, but I guess they changed some styles, so .. now things don't work as expected anymore.

**Actual behavior**
Everything is grey instead of black.

**Screenshots**

image

image

**System info:**

- OS: MacOS
- Browser: Firefox 82.0.3 (64-bit)
- Darkreader Version: 4.9.23

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Gusted**
- If the theme settings are different from the default one, modify the variables to match the settings.
- Resolves #4182

### CODE REVIEW

**Comment by Gusted** [comment]
Compiled code:
[builds.zip](https://github.com/darkreader/darkreader/files/5577176/builds.zip)

File: src/inject/dynamic-theme/index.ts [hunk 1]
```diff
@@ -108,11 +109,22 @@ function createStaticStyleOverrides() {
 
     const variableStyle = createOrUpdateStyle('darkreader--variables');
     const selectionColors = getSelectionColor(filter);
-    const {darkSchemeBackgroundColor, darkSchemeTextColor, lightSchemeBackgroundColor, lightSchemeTextColor} = filter;
+    const {darkSchemeBackgroundColor, darkSchemeTextColor, lightSchemeBackgroundColor, lightSchemeTextColor, mode, brightness, contrast, sepia, grayscale} = filter;
+    let schemeBackgroundColor = mode === 0 ? lightSchemeBackgroundColor : darkSchemeBackgroundColor;
+    let schemeTextColor = mode === 0 ? lightSchemeTextColor : darkSchemeTextColor;
+    if (brightness !== 100 || contrast !== 100 || sepia !== 0 || grayscale !== 0) {
```
Comment (alexanderby) [inline src/inject/dynamic-theme/index.ts:115]: Worth replacing this block with
```javascript
schemeBackgroundColor = modifyBackgroundColor(parse(schemeBackgroundColor), filter);
schemeTextColor = modifyForegroundColor(parse(schemeTextColor), filter);
```

It looks like shorter and equivalent. You can also remove `...brightness !== 100 || ...` because it looks like micro optimization here (called just 1 time).

**Review by alexanderby — CHANGES_REQUESTED** [review]

**Review by nulh — COMMENTED** [review]
[darkreader/darkreader] End-to-end tests (#4267)

File: src/inject/dynamic-theme/index.ts (hunk 1 above)
Comment (Gusted) [reply src/inject/dynamic-theme/index.ts]: Forgot that we don't need to check because modifying the pole color with default settings will return the pole color.

**Review by alexanderby — APPROVED** [review]
