### PR TITLE
Fix render bug for protected sites

### LINKED ISSUE #3548: [BUG] protected pages cannot be disabled when granted permission
### **Describe the bug**

 If a protected page is allowed to be modified by darkreader, that page cannot be toggled

### **Expected behavior**

If you grant permission for darkreader to work on protected pages, the dark mode should be able to be toggled just like another website.

### **Screenshots**

Dark mode cannot be disabled on addons.mozilla.org (recommendation of Dark Reader is by pure chance):
image
I tried screenshotting the settings window but it disappears when I capture the picture.

### **System Information:**
 - OS: Ubuntu 20.04
 - Browser: Firefox 81 beta
 - Dark Reader version: GitHub development snapshot mentioned on #3533

### PR DESCRIPTION
**Pull request by Gusted**
- tab.isProtected should not use `enableForProtectedPages` option as it doesn't get up-to-date data and will return the old value.
- Real-time site-toggle disable according isProtected logic and `enableForProtectedPages` option.
- Make test according to the good visa-versa logic(Forgot to update in previous PR)
- Resolves #3548

### CODE REVIEW

**Comment by Gusted** [comment]
@erkinalp 
Commit https://github.com/darkreader/darkreader/pull/3549/commits/fb99c33727d80b8a26ecc910a360c9c61f315ce4 fixed this reversed behavior and is now behaving how it should be.

**Review by erkinalp — APPROVED** [review]
thanks

**Comment by erkinalp** [comment]
another bug: non-protected pages cannot be toggled now if you disable "enable on protected pages".

**Comment by Gusted** [comment]
Shit here we go again.

**Comment by Gusted** [comment]
@erkinalp 
Are you sure? I tried a fresh `npm run debug` of this branch and it just behaves how it should be. Maybe something in your sitelist?

**Comment by erkinalp** [comment]
Certainly not. I tried a `npm run release`, though.

**Comment by Gusted** [comment]
> You know, it is a thing that some things only fail in release builds.

You know, the thing with our build workflow. The output of the code is always the same and gives identical(Other than some more debug info and a inline-source-map that doesn't affect the actual code) output and results.

 

> Certainly sure. I tried a `npm run release`,

Noppes and nana, it still works. I suggest to remove the extension and than re-side-load it.

**Comment by erkinalp** [comment]
Re-side loaded but still having the same problem.

**Comment by Gusted** [comment]
What if you try to sideload [this version of the branch](https://github.com/darkreader/darkreader/files/5147339/darkreader.zip)

**Comment by erkinalp** [comment]
That version fixed the problem :1st_place_medal:

**Comment by Gusted** [comment]
Well, that was commit https://github.com/darkreader/darkreader/pull/3549/commits/6b309fdddc5b60d606da78d4b961bdbc03dea137 but than `npm run debug`

File: src/ui/popup/components/site-toggle/index.tsx [hunk 1]
```diff
@@ -15,7 +15,7 @@ export default function SiteToggleButton({data, tab, actions}: ExtWrapper & {tab
     }
     const toggleHasEffect = (
         data.isEnabled &&
-        !tab.isProtected
+        data.settings.enableForProtectedPages ? true : !tab.isProtected
```
Comment (alexanderby) [inline src/ui/popup/components/site-toggle/index.tsx:18]:
```javascript
(data.settings.enableForProtectedPages || !tab.isProtected)
```

**Review by alexanderby — CHANGES_REQUESTED** [review]

**Review by alexanderby — APPROVED** [review]

**Review by Scutua — APPROVED** [review]
