### PR TITLE
PDF Toggle URL

### LINKED ISSUE #2439: [BUG] Clicking the website toggle button should toggle PDF too
Clicking the website toggle button (in the top left corner) should toggle PDF files too.

**Steps to reproduce the behavior**
- Open a PDF document.
- Click Toggle button.

**Expected behavior**
Extension stops inverting PDF file (or inverts if was disabled before).

**Actual behavior**
PDF is still inverted.

**Screenshots**

### PR DESCRIPTION
**Pull request by Gusted**
Resolved #2439

### CODE REVIEW

File: src/ui/popup/components/site-toggle/index.tsx [hunk 1]
```diff
@@ -1,19 +1,21 @@
...
-import {getURLHost, isURLEnabled} from '../../../../utils/url';
+import {getURLHost, isURLEnabled, isPDF} from '../../../../utils/url';
 import {ExtWrapper, TabInfo} from '../../../../definitions';
 
 export default function SiteToggleButton({data, tab, actions}: ExtWrapper & {tab: TabInfo}) {
     const toggleHasEffect = (
         data.isEnabled &&
         !tab.isProtected
     );
+    const PDF = isPDF(tab.url);
```
Comment (alexanderby) [inline src/ui/popup/components/site-toggle/index.tsx:12]: There is a convention to use uppercase only for hard-coded values.

File: src/ui/popup/components/site-toggle/index.tsx [hunk 2]
```diff
@@ -1,19 +1,21 @@
...
     const isSiteEnabled = isURLEnabled(tab.url, data.settings, tab);
     const host = getURLHost(tab.url || '');
 
     const urlText = (host
         ? host
+
```
Comment (alexanderby) [inline src/ui/popup/components/site-toggle/index.tsx:18]: Extra new line appeared.

File: src/ui/popup/components/site-toggle/index.tsx [hunk 3]
```diff
@@ -25,10 +27,10 @@ export default function SiteToggleButton({data, tab, actions}: ExtWrapper & {tab
         <Button
             class={{
                 'site-toggle': true,
-                'site-toggle--active': isSiteEnabled,
+                'site-toggle--active': isSiteEnabled || PDF,
```
Comment (alexanderby) [inline src/ui/popup/components/site-toggle/index.tsx:30]: I think it should be `pdf ? data.settings.enableForPDF : isSiteEnabled`.

File: src/ui/popup/components/site-toggle/index.tsx [hunk 4]
```diff
@@ -25,10 +27,10 @@ export default function SiteToggleButton({data, tab, actions}: ExtWrapper & {tab
...
                 'site-toggle--disabled': !toggleHasEffect
             }}
-            onclick={() => actions.toggleURL(tab.url)}
+            onclick={() => PDF ? actions.changeSettings({enableForPDF: !data.settings.enableForPDF}) : actions.toggleURL(tab.url)}
```
Comment (alexanderby) [inline src/ui/popup/components/site-toggle/index.tsx:33]: Good, but I feel like it's better to move such long lines out of attribute. Declare an event handler somewhere above.

The problem with JSX is that it becomes less readable with complex logic inside. Also when the layout changes, all this logics shifts too. This makes it harder to use tools like `git blame`, or review PRs.

File: src/ui/popup/components/site-toggle/index.tsx [hunk 5]
```diff
@@ -1,14 +1,23 @@
 import {m} from 'malevic';
 import CheckmarkIcon from './checkmark-icon';
 import {Button} from '../../../controls';
-import {getURLHost, isURLEnabled} from '../../../../utils/url';
+import {getURLHost, isURLEnabled, isPDF} from '../../../../utils/url';
 import {ExtWrapper, TabInfo} from '../../../../definitions';
 
 export default function SiteToggleButton({data, tab, actions}: ExtWrapper & {tab: TabInfo}) {
+
+    function click() {
```
Comment (alexanderby) [inline src/ui/popup/components/site-toggle/index.tsx:9]: There is a convention :) ... to start event handlers with `on` (like `onClick`), to describe what is being clicked (like `onSiteToggleClick`) or describe the event, rather than DOM action (`onSiteToggle`, maybe it could be reaction on click, keypress etc). Some people prefer to add `-handler` or `-listener` (like `siteToggleHandler`).

File: src/ui/popup/components/site-toggle/index.tsx [hunk 6]
```diff
@@ -25,10 +34,10 @@ export default function SiteToggleButton({data, tab, actions}: ExtWrapper & {tab
         <Button
             class={{
                 'site-toggle': true,
-                'site-toggle--active': isSiteEnabled,
+                'site-toggle--active': pdf ? data.settings.enableForPDF : isSiteEnabled,
                 'site-toggle--disabled': !toggleHasEffect
             }}
-            onclick={() => actions.toggleURL(tab.url)}
+            onclick={onSiteToggleClick()}
```
Comment (alexanderby) [inline src/ui/popup/components/site-toggle/index.tsx:40]: You are calling the function, but it should be passed as a property.
