### PR TITLE
Expose CSS fixes to Shadow Roots

### LINKED ISSUE #3652: [Broken Website] ea.com
**Website**
https://www.ea.com/news/ea-desktop-app

**How to Reproduce**

> 1. Go to the site

**Expected behavior**
Dark background, also try to log in

**Actual behavior**
Light background

**System info:**
 - OS: Windows
 - Browser: Firefox
 - Darkreader Version: 4.9.19

### PR DESCRIPTION
**Pull request by Gusted**
- Expose Dynamic theme fixes to shadow-roots so it can be fixed as well.
- Removed a depcrated option in createTreeWalker
- Resolves #3652

### CODE REVIEW

File: src/inject/utils/dom.ts [hunk 1]
```diff
@@ -173,7 +173,6 @@ export function iterateShadowHosts(root: Node, iterator: (host: Element) => void
                 return (node as Element).shadowRoot == null ? NodeFilter.FILTER_SKIP : NodeFilter.FILTER_ACCEPT;
             }
         },
-        false,
```
Comment (alexanderby) [inline src/inject/utils/dom.ts:176]: Not sure what this parameter was there for. Hope nothing will break.

**Review by alexanderby — APPROVED** [review]

File: src/inject/utils/dom.ts (hunk 1 above)
Comment (Gusted) [reply src/inject/utils/dom.ts:176]: I only know it's been decrapted for 2 years. 
https://github.com/Microsoft/TypeScript/blame/master/lib/lib.dom.d.ts#4766
