### PR TITLE
Use a new mechanism to inject Fallback

### LINKED ISSUE #3593: [Broken Website] https://personal.vanguard.com
**Website**
https://personal.vanguard.com/us/faces/com/vanguard/logon/view/LogonLogoff.xhtml

**How to Reproduce**
 1. Go to https://personal.vanguard.com/us/faces/com/vanguard/logon/view/LogonLogoff.xhtml
2. Blank Page. 

**Expected behavior**
There should be content when I go to that page. Makes vanguard.com unusable. When you turn off Dark reader content renders fine.

**Actual behavior**
After login the website should render, but it does not.

**System info:**
 - OS:MacOS
 -  chrome
 - Darkreader Version: latest

### LINKED ISSUE #3653: [BUG] Roundcube Mail is broken if Dark Reader 4.9.17 or later is loaded (even if inactive)
### **Describe the bug**

Roundcube Mail web client cannot save or send email when Dark Reader 4.9.17 is loaded (even if inactive). First noticed with 4.9.19 as the updates from 4.9.17 onward happened while I wasn't using this system

### **Steps to reproduce**

This is tricky - you need an instance of Roundcube Mail to try this with, and it's not something you'd normally have public access to

### **Expected behavior**

Roundcube Mail should work normally

### **Actual behavior**

When sending an email or saving a draft, Roundcube just hangs until it finally times out.

### **System Information:**

Affects Roundcube 1.41 and 1.48 (I upgraded in the midst of debugging this) via Windows 10 Chrome 85.0.4183.83 (Official Build) (64-bit). Also fails via current 85.0.4183.102 (Official Build) (64-bit). This appears to have broken recently - within the last 10 days or less.

### **Additional context**

I've been using Dark Reader for years, and have never seen this happen. I first thought it was RC not working right with newer Chrome, but I narrowed it down to Dark Reader - even if I disable every other extension this one alone will break RC Mail in a way it didn't do 10 days or so ago when I last used it on this machine.

**I was able to find the original CRX fles for Dark Reader 4.9.16 through 4.9.19. After carefully editing the manifest to prevent upgrade, I was able to load each in turn unpacked, and confirm that 4.9.16 was the last version that worked properly in this regard.**

### PR DESCRIPTION
**Pull request by Gusted**
- Use the `createNodeAsap` logic to make sure the fallback will be injected correctly into the site.
- Use the logic to already create a `head` and append the fallback style into that.
- Resolves #3653
- Resolves #3593

### CODE REVIEW

File: src/inject/fallback.ts [hunk 1]
```diff
@@ -1,11 +1,34 @@
...
     matchMedia('(prefers-color-scheme: dark)').matches &&
     !document.querySelector('.darkreader--fallback')
 ) {
-    const fallbackStyle = document.createElement('style');
-    fallbackStyle.textContent = 'html, body, body :not(iframe) { background-color: #181a1b !important; border-color: #776e62 !important; color: #e8e6e3 !important; }';
-    document.documentElement.appendChild(fallbackStyle);
-    fallbackStyle.classList.add('darkreader');
-    fallbackStyle.classList.add('darkreader--fallback');
-    fallbackStyle.media = 'screen';
+    createOrUpdateFallback('html, body, body :not(iframe) { background-color: #181a1b !important; border-color: #776e62 !important; color: #e8e6e3 !important; }');
```
Comment (alexanderby) [inline src/inject/fallback.ts:7]: Put the CSS string into some constant.

File: src/inject/fallback.ts [hunk 2]
```diff
@@ -1,11 +1,34 @@
...
+        selectNode: () => document.querySelector('darkreader--fallback'),
+        createNode: (target) => {
+            const fallbackStyle = document.createElement('style');
+            fallbackStyle.textContent = css;
+            target.appendChild(fallbackStyle);
+            fallbackStyle.classList.add('darkreader');
+            fallbackStyle.classList.add('darkreader--fallback');
+            fallbackStyle.media = 'screen';
+        },
+        updateNode: (existing) => {
```
Comment (alexanderby) [inline src/inject/fallback.ts:21]: I think `updateNode` can be an empty NOOP function in this case, like `Function.prototype`. If there will be a fallback style, it will not do anything.

File: src/inject/fallback.ts [hunk 3]
```diff
@@ -1,11 +1,34 @@
...
-    document.documentElement.appendChild(fallbackStyle);
-    fallbackStyle.classList.add('darkreader');
-    fallbackStyle.classList.add('darkreader--fallback');
-    fallbackStyle.media = 'screen';
+    createOrUpdateFallback('html, body, body :not(iframe) { background-color: #181a1b !important; border-color: #776e62 !important; color: #e8e6e3 !important; }');
+}
+
+export function createOrUpdateFallback(css: string) {
+    createNodeAsap({
+        selectNode: () => document.querySelector('darkreader--fallback'),
```
Comment (alexanderby) [inline src/inject/fallback.ts:12]: Missing dot `.` in the selector

File: src/inject/fallback.ts [hunk 4]
```diff
@@ -1,11 +1,34 @@
...
-    const fallbackStyle = document.createElement('style');
-    fallbackStyle.textContent = 'html, body, body :not(iframe) { background-color: #181a1b !important; border-color: #776e62 !important; color: #e8e6e3 !important; }';
-    document.documentElement.appendChild(fallbackStyle);
-    fallbackStyle.classList.add('darkreader');
-    fallbackStyle.classList.add('darkreader--fallback');
-    fallbackStyle.media = 'screen';
+    createOrUpdateFallback('html, body, body :not(iframe) { background-color: #181a1b !important; border-color: #776e62 !important; color: #e8e6e3 !important; }');
+}
+
+export function createOrUpdateFallback(css: string) {
```
Comment (alexanderby) [inline src/inject/fallback.ts:10]: Is there a need to export the function?

**Review by alexanderby — CHANGES_REQUESTED** [review]

File: src/inject/fallback.ts [hunk 5]
```diff
@@ -1,11 +1,31 @@
...
-    fallbackStyle.textContent = 'html, body, body :not(iframe) { background-color: #181a1b !important; border-color: #776e62 !important; color: #e8e6e3 !important; }';
-    document.documentElement.appendChild(fallbackStyle);
-    fallbackStyle.classList.add('darkreader');
-    fallbackStyle.classList.add('darkreader--fallback');
-    fallbackStyle.media = 'screen';
+    const fallBackCSS = 'html, body, body :not(iframe) { background-color: #181a1b !important; border-color: #776e62 !important; color: #e8e6e3 !important; }';
+    createOrUpdateFallback(fallBackCSS);
+}
+
+function createOrUpdateFallback(css: string) {
```
Comment (alexanderby) [inline src/inject/fallback.ts:11]: I don't see a purpose of passing `css` argument, it is always the same.

File: src/inject/fallback.ts [hunk 6]
```diff
@@ -1,11 +1,31 @@
+import {createNodeAsap} from './utils/dom';
+
 if (
```
Comment (alexanderby) [inline src/inject/fallback.ts:3]: Let's add `document.documentElement instanceof HTMLHtmlElement` condition, so that it will not inject anything into SVGs and other strange files.

**Review by alexanderby — CHANGES_REQUESTED** [review]

**Review by alexanderby — APPROVED** [review]
