### PR TITLE
Export contents to Clipboard

### LINKED ISSUE #2999: [BUG] Export settings as JSON file don't work on Vivaldi Browser
### **Describe the bug**

Export settings as JSON file don't work on Vivaldi Browser. There is no file launched for downloading. It doesn't seem to me that there's a console error

### **Steps to reproduce**

- Click on Dark Reader button
- Click on Dev tools (in the bottom-right corner)
- Click on Preview new design
- Click on Settings
- Click on Manage settings
- Click on Export Settings

### **Expected behavior**

There should be a JSON file added to the download list.

### **Actual behavior**

Nothing's happening.

### **System Information:**
 - OS: W10 Pro x64 1909 (18363.900)
 - Browser: Vivaldi v3.1.1929.45 (Stable channel) (64 bits)
 - Dark Reader version: v4.9.13

### PR DESCRIPTION
**Pull request by Gusted**
- Export settings to Clipboard 
- Resolves #2999

### CODE REVIEW

**Comment by alexanderby** [comment]
Let's determine the exact error.
Does any of these downloads work?
1. Current https://jsfiddle.net/c3k5zbuw/
2. Data URL https://jsfiddle.net/ynLrvwuc/

File: src/ui/popup/manage-settings-page/export-settings.tsx [hunk 1]
```diff
@@ -5,7 +5,7 @@ import {saveFile} from '../../utils';
 import ControlGroup from '../control-group';
 
 export default function ExportButton(props: ViewProps) {
-    function exportSettings() {
+    async function exportSettings() {
```
Comment (alexanderby) [inline src/ui/popup/manage-settings-page/export-settings.tsx:8]: This function seems like synchronous.
