### PR TITLE
Fix #1621: Fix the Duplication of text for all shortcuts

### LINKED ISSUE #1621: "Toggle current site" shortcut duplicates when clicking another button.
When using the extension on Firefox and interacting with the extension overlay there is a visual bug when clicking the "Toggle current site" shortcut which causes it to duplicate.

Peek 2019-10-10 07-17

### PR DESCRIPTION
**Pull request by RyanWils**
Steps to solving this issue 

When another button is clicked it 
In this function listed below it matches the parents/siblings 
image
It then calls the insertNode function and inserts the shortcut message again 
image
When its sets the shortcut it goes into this function
image

The code I added does the following
    //create variables for both the toggle switches
    const shortcutClass = document.getElementsByClassName("shortcut");
    const toggleCurrent = document.getElementsByClassName("shortcut").item(0);
    const toggleExtension = document.getElementsByClassName("shortcut").item(1);

    //If all the toggles come back in the class, it means that the shortcuts exist and its not the 
    creation
    if (shortcutClass.length == 3) {
        //Check to see if there is any repeats of Toggle 
        if (toggleCurrent.innerHTML.lastIndexOf("Toggle") > 5) {
            //if there is repeats then take the first instance of the string (Example of what the string 
            looks like "Toggle extension\nAlt+Shift+DToggle extension\nAlt+Shift+D")
            toggleCurrent.innerHTML = 
            toggleCurrent.innerHTML.slice(0,toggleCurrent.innerHTML.indexOf("Toggle",1));
        }
        //Same logic for the extension button 
        if (toggleExtension.innerHTML.lastIndexOf("Toggle") > 5) {
            toggleExtension.innerHTML = 
            toggleExtension.innerHTML.slice(0,toggleExtension.innerHTML.indexOf("Toggle",1));
        }
    }

### CODE REVIEW

File: src/ui/controls/shortcut/index.tsx [hunk 1]
```diff
@@ -18,6 +18,18 @@ interface ShortcutLinkProps {
 export default function ShortcutLink(props: ShortcutLinkProps) {
     const cls = mergeClass('shortcut', props.class);
     const shortcut = props.shortcuts[props.commandName];
+    const shortcutClass = document.getElementsByClassName("shortcut");
```
Comment (alexanderby) [inline src/ui/controls/shortcut/index.tsx]: Hi, thanks for the provided solution. However it looks like a hack. The `ShortcutLink` class should know nothing about its implementations.

File: src/ui/controls/shortcut/index.tsx [hunk 2]
```diff
@@ -18,6 +18,18 @@ interface ShortcutLinkProps {
...
+    const toggleCurrent = document.getElementsByClassName("shortcut").item(0);
+    const toggleExtension = document.getElementsByClassName("shortcut").item(1);
+
+    if (shortcutClass.length == 3) {
+        if (toggleCurrent.innerHTML.lastIndexOf("Toggle") > 5) {
+            toggleCurrent.innerHTML = toggleCurrent.innerHTML.slice(0,toggleCurrent.innerHTML.indexOf("Toggle",1));
```
Comment (alexanderby) [inline src/ui/controls/shortcut/index.tsx]: Use of `innerHTML` is discouraged.

**Comment by RyanWils** [comment]
@alexanderby 
Hi Alexander, Thanks for reviewing this Pull Request. 
Steps to why this occurs,
1. Initial variable is set to node.textcontext
2. It creates the node with the text ("Toggle Extension\nCtrl+D") when you click on the button cause it re renders the elements. 
3. it sets it the node.textcontext to the initial in the OnBlur function.  

This OnBlur function was mainly used to reset the text when you click on the toggle and then click off it.
I will look deeper into this issue.

File: src/ui/controls/shortcut/index.tsx (hunk 2 above)
Comment (RyanWils) [reply src/ui/controls/shortcut/index.tsx]: My logic for this issue consists of the following
1. If node.content is equal to "..." then set it to the initial text
2. If node.content is equal to "Toggle" then do not set the node context node as this means that it was already created by the re render function.

But the issue that I ran into was that there was no actual way to get the node.content so I grabbed the InnerHTML.

File: src/ui/controls/shortcut/index.tsx (hunk 1 above)
Comment (RyanWils) [reply src/ui/controls/shortcut/index.tsx]: From my knowledge props.shortcuts just stored the shortcuts to toggle the site, not the node.content.
Notice this behaviour 
image
I added a test message to the end of the line
image

What I assume it did 
1.set the text of the node  "Toggle Extension\nCtrl+D"
2.append the initial "Toggle Extension\nCtrl+Dtest"

String is now - "Toggle Extension\nCtrl+DToggle Extension\nCtrl+Dtest"

1. inital = node.content 
1.set the text of the code "Toggle Extension\nCtrl+D"
2. append the initial "Toggle Extension\nCtrl+DToggle Extension\nCtrl+Dtest" + "test" 

String is now "Toggle Extension\nCtrl+DToggle Extension\nCtrl+DToggle Extension\nCtrl+Dtesttest"

Refer to my comment below

**Comment by alexanderby** [comment]
[Here](https://github.com/alexanderby/malevic/blob/master/tests/dom.tests.tsx) are various DOM tests. But they are run in js-dom environment, so maybe the problem will not be reproducible. Also, maybe it is expected problem if you mix virtual DOM with real DOM manipulation.

So, maybe let's not use Virtual DOM for text content in this case and always stick to using `textContent` property. Malevič.js has ability to pass a function, that will be executed after parent DOM node was updated, like:
```jsx
function Component(props) {
    return <div>
        {(domNode) => domNode.textContent = props.text}
    </div>;
}
```

**Comment by RyanWils** [comment]
@alexanderby Hi Alexander,
Sorry for the late reply. I have been exploring through the Malevič.js documentation and I am pretty new to using Malevič.js, so there's a lot of grey areas.
As you talked about not sure if its the same thing, but the after the parent nodes are updated it will pass a function. 
I have submitted another commit which fixes the duplicates text using the OnUpdate function.
Not sure if this is an appropriate fix, feedback would be appreciated.

File: src/ui/controls/shortcut/index.tsx [hunk 3]
```diff
@@ -88,11 +89,16 @@ export default function ShortcutLink(props: ShortcutLinkProps) {
         });
     }
 
+    function onUpdate(props) {
```
Comment (alexanderby) [inline src/ui/controls/shortcut/index.tsx]: Let's rename this function to `on Render` (see why later). `props` is an HTMLElement (HTMLAElement to be more precise), we can rename the argument and add a type to it (since we are using TypeScript).

File: src/ui/controls/shortcut/index.tsx [hunk 4]
```diff
@@ -88,11 +89,16 @@ export default function ShortcutLink(props: ShortcutLinkProps) {
...
+        props.textContent = shortcutMessage;
+    }
+
     return (
         <a
             class={cls}
             href="#"
             onclick={onClick}
+            updated={onUpdate}
```
Comment (alexanderby) [inline src/ui/controls/shortcut/index.tsx]: Let's add `attached={onRender}`. `attached` handler is invoked after DOM element is created and attached to DOM for the first time, `updated` is called after DOM was synchronized with virtual DOM. I had an idea to add `rendered` handler that would be called in both cases.

File: src/ui/controls/shortcut/index.tsx [hunk 5]
```diff
@@ -88,11 +89,16 @@ export default function ShortcutLink(props: ShortcutLinkProps) {
...
         >{props.textTemplate(shortcut)}</a>
```
Comment (alexanderby) [inline src/ui/controls/shortcut/index.tsx]: The problem was in this line, it creates a string and a virtual text node is created for it. But since we use real DOM manipulations, let's make text empty. We can just leave it as `<a ... />`.

**Comment by RyanWils** [comment]
I have put in your requested changes. 
It seems that the attached function is used in other parts of the code and the parameter was not casted for example
image
To keep the code consistent I did not cast (HTMLAnchorElement) to the node.
image
